### PR TITLE
proxy: add a insecure_skip_verify option - closes #320

### LINKED ISSUE #320: Proxy to a remote server with the remote using self signed certs fails.
Suppose that you have caddy running as a reverse proxy to a 2nd server.  Caddy will return
an error if the 2nd server has self signed certificates.

Caddyfile:
```
https://localhost:3223 {
	tls /Users/corwin/Projects/ws2/samp-key/cert.pem /Users/corwin/Projects/ws2/samp-key/key.pem
	proxy /static https://www.test2.com:9443/
}
```

Suppose that https://www.test2.com:9443/ is a server running with self-signed certificates.
You get the error:

2015/11/05 09:00:00 http: TLS handshake error from 192.168.0.158:56996: remote error: bad certificate

The :9443 server is in Go with HTTP2.0.  I can provide the source code for it if you need it.

### PR DESCRIPTION
**Pull request by FiloSottile**

### CODE REVIEW

**Comment by mholt** [comment]
This is an elegant fix, thanks. Looks good -- just trying to commit myself to the name "insecure_skip_verify" :smile: I'm leaning toward keeping that, but "weak_https", "unsafe_https", and "allow_invalid_certs" come to mind. Any preferences?

**Comment by abiosoft** [comment]
I personally think just `unsafe` is enough.

**Comment by mholt** [comment]
It would be good to add a test case for this, too. The test would generate a self-signed cert in memory and start up a backend server, then try to proxy a request to it and it should succeed.

**Comment by mholt** [comment]
After sleeping on it -- I like it. So I'll merge this in but am making a note that this needs a test soon. Thanks Filippo!

**Comment by mholt** [comment]
Got a test in 82b049229b5c6d91ed665a0280e9c1e7ffaddc27

**Pull request merged**
