### PR TITLE
Proxy: Add a failing test which replicates #763

### PR DESCRIPTION
**Pull request by edrex**
2 websocket connections are made instead of one

### CODE REVIEW

**Comment by mholt** [comment]
Ooo, nice catch. Will look into this soon, thanks!

**Comment by mholt** [comment]
It appears that the first connection comes from the [RoundTrip of the initial request](https://github.com/mholt/caddy/blob/b75016e646034d0682a3753949462c5858cb3943/middleware/proxy/reverseproxy.go#L205), which is needed to find out it is a websocket connection. Then we [dial in as a websocket client](https://github.com/mholt/caddy/blob/b75016e646034d0682a3753949462c5858cb3943/middleware/proxy/reverseproxy.go#L223) to establish the websocket connection.

Are we doing it wrong? O.o

**Comment by edrex** [comment]
i'm looking into this

**Comment by edrex** [comment]
I'm looking into this

**Comment by edrex** [comment]
I found two client implementations that actually do the handshake.

github.com/gorilla/websocket Dials the connection first and then [passes it to req.Write](https://github.com/gorilla/websocket/blob/master/client.go#L284)

[golang.org/x/net/websocket#NewClient](https://godoc.org/golang.org/x/net/websocket#NewClient) skips the `http` package and just writes everything out directly.

I'll probably look into doing what Gorilla does in the morning. This should be fixed right away, but maybe eventually using one of these client implementations would be a good idea?

**Comment by mholt** [comment]
It's also interesting [how they set the header names to be careful about casing](https://github.com/gorilla/websocket/blob/e2e3d8414d0fbae04004f151979f4e27c6747fe7/client.go#L196-L206)

I'd be fine with using gorilla. But remember, we're first an HTTP proxy -- we can't assume that all requests are websocket connections. Only the responses with the proper Upgrade header should be turned into websockets.

**Comment by edrex** [comment]
The main obstacle to a quick fix is that the RoundTripper interface doesn't expose the net.Conn it creates. It seems like the interface would have to change to take a Dial function and any other values needed to construct the RoundTripper.

Another possibility would be to move websocket proxying into the `websocket` directive, possibly with an `upstream` param taking `ws://` and `wss://` URLs, but that would be a breaking change.

**Comment by mholt** [comment]
@edrex We could use a type assertion to get our concrete type out of the RoundTripper if needed...

**Comment by edrex** [comment]
I pushed up a refactor which concretizes the type of ReverseProxy#Transport, hopefully preparing to dial manually etc. Test still fails at this point.

**Comment by mholt** [comment]
Hey Eric, nice work so far. Any luck bringing it full circle to make the test pass?

**Comment by edrex** [comment]
I tried to get something working using github.com/koding/websocketproxy, intending to pull out the needed logic once it worked, but I never got the test to pass. Sorry to drop the ball on this, just haven't had a chance to dig in and get it working. I pushed up my WIP, so if anyone wants to continue this let me know. If not I will likely come back to it in a week or two.

**Comment by mholt** [comment]
Nice start!! I'm not in a hurry for this, as I've still got my hands tied up with 0.9 work. The fix is definitely important but don't feel rushed. Of course I encourage other contributors to help out if they want this fix sooner than later. :+1:

**Comment by mholt** [comment]
Hi. :smile: Should we keep this PR open?

**Comment by edrex** [comment]
Feel free to close, since I haven't gotten back to it. Currently I don't have the slack to context switch. I can always request reopen :)

**Comment by edrex** [comment]
I'll close, since I haven't gotten back to it. Currently I don't have the slack to context switch.

**Comment by mholt** [comment]
Sounds good to me. Thanks!

**Pull request closed without merging**
