### PR TITLE
Enable downloading of protected content. See issue #979

### PR DESCRIPTION
**Pull request by slightfoot**
Please see issue #979

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for the PR Simon! This looks good but perhaps we should have a test to assert that only the desired headers are removed. Could you write a test before we merge this?

**Comment by slightfoot** [comment]
I'll see what I can do.

**Comment by slightfoot** [comment]
@mholt Sorry for the delay. Tests added.

**Comment by mholt** [comment]
Nice! Thanks for your contribution, @slightfoot! We'll give it a go.

**Pull request merged**
