### PR TITLE
capitalize struct name in comment

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by shawnps** [comment]
@mholt is there a way to sign the CLA without using this external tool?

**Comment by mholt** [comment]
@shawnps Hmm, not that I know of; are you having trouble with it?

If it's a problem I could just make the change locally and be very grateful to you for opening the PR :stuck_out_tongue:

**Comment by shawnps** [comment]
@mholt just curious :) Thanks!

**Comment by mholt** [comment]
Thanks Shawn!

**Pull request merged**
