### PR TITLE
Add "supervisor" directive

### PR DESCRIPTION
**Pull request by lucaslorentz**
### 1. What does this change do, exactly?
Adds "run" directive that will be used by plugin https://github.com/lucaslorentz/caddy-run

### 2. Please link to the relevant issues.
N/A

### 3. Which documentation changes (if any) need to be made because of this PR?
N/A

### 4. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### Comments
I created this plugin because I find it useful to run .NET Core applications and also php cgi.
It is different from the **on** plugin, because it is not event driven and also ensures the application keeps running in background with several extra options and restart policy.
Let me know if you already have plans for directive name **run**, I can easily rename the plugin.
I've been testing it mainly on windows, tests, suggestions and feedback are welcome.
After this PR get's merged I will add it to caddy plugins list.

### CODE REVIEW

**Comment by mholt** [comment]
Woah, hey, Lucas -- this is awesome. But before going further, I think you and I should chat.

1) I'd rather improve the `on` directive rather than make a new directive just to add new features for essentially the same functionality as already exists.

2) Better yet -- how about a server type instead of a single directive? https://caddy.community/t/brainstorming-a-caddy-server-type-for-processes-commands/2184?u=matt

Number 2, the server type plugin, has been a brainchild of mine for almost two years now but I've never had time to sit down and write it. I'd love to move away from systemd and other similar options as much as possible because of their immense complexities and poor documentation. I think your `run` plugin is, in fact, a perfect start of something that I and probably others who want to move away from systemd a little bit would use. (It wouldn't fully replace systemd, of course, just the process management stuff!)

Whichever path we go down, it won't undo the work you put into this plugin, since it will either reuse the code you already wrote or build from it as it transforms into something else.

What do you think?

**Comment by francislavoie** [comment]
If I'm reading this right, this is kinda like supervisord, right? If so, that's awesome and I could totally make use of it. I'd love to see features like number of processes (spawning X number of workers) and such. I think this would be a great fit with Caddy to run background job queue workers.

**Comment by magikstm** [comment]
I'm curious if it may help resolve an issue discussed recently in the forum:
https://caddy.community/t/fast-cgi-and-php-on-windows/3432/7

**Comment by francislavoie** [comment]
@magikstm I think out of the box it wouldn't because it won't forward requests down to the process being run. I think it's more for long-running processes/servers.

**Comment by magikstm** [comment]
@francislavoie I think it possibly could based on the example @lucaslorentz mentioned on the main page of the plugin:
```
example.com {
  run {
    command ./php-cgi.exe
    args -b 9800
    dir C:/php/
    redirect_stdout stdout
    redirect_stderr stderr
    restart_policy always
  }
  root C:/Site
  fastcgi / localhost:9800 php
}
```

Ref: https://github.com/lucaslorentz/caddy-run

**Comment by lucaslorentz** [comment]
@mholt 

1. I thought about expanding or using the **on** directive, but it is clearly event driven. While running a sub processes in background is not related to events, it should always be running, be restarted, and be killed when caddy exits. For me they are 2 different concepts. We could merge both concepts, but in my point of view it would imply renaming the **on** directive.

2. That's a very different approach. From what I understood, I could use that process management tool without running any network related server. If that's the case, I think it deserves a separate repository and name.

Feel free to start something else from it.
I'm afraid I can't maintain anything more complex than that directive plugin, due to time restriction and golang experience.
I would migrate to it as soon as it becomes available and allows me to mix proxy directives with the execution of my target application.
For me it's even better if it is maintained by core caddy developers!

Do you think we should merge this directive name and register it as a plugin for now?
I would love to remove this line:
https://github.com/lucaslorentz/caddy-run/blob/master/build.sh#L10 😄

**Comment by lucaslorentz** [comment]
@francislavoie 
Yes, it's similar. But with less ambitions. This plugin would be a good fit to run nodejs/go/.net applications along with caddy.

I would love to see it dynamically spawn workers based on the load. But I don't know how that could be combined with a proxy directive, since each worker would use a different port, and the amount of workers would vary.

Maybe we can start with fixed amount of workers + go templates allowing change settings based on the current worker. Something like:
```
run {
  command myapp
  args --port {{add 8001 .replicaIndex}}
  replicas 5
}
proxy / localhost:8001-8005
```

**Comment by lucaslorentz** [comment]
@magikstm @francislavoie 
I got PHP working with fastcgi as described in the example in https://github.com/lucaslorentz/caddy-run
The only thing I have extra that I didn't put on the example is some rewrites for wordpress

**Comment by francislavoie** [comment]
@lucaslorentz for dynamic worker counts, `run` could plug into a specific `proxy` directive's upstream list. You could add/remove from the `upstream` list dynamically. Would probably need changes to `proxy` to support it, but I think that would be awesome. Personally, I'd be ok with just having a set amount of workers, the dynamic part isn't as important.

**Comment by lucaslorentz** [comment]
@mholt 
Regarding a feature like increasing the number of workers based on the number of active requests.
I think that feature doesn't fit well the **on** directive.
Neither fit well the separate server type, because it is http related.

Maybe in the end we should keep the 3 things 😄
**On** directive
**Run** directive inside http server
New server type

**Comment by lucaslorentz** [comment]
Hey @mholt 
Just a gentle ping about this thread.
I'm looking forward for your thoughts and some instructions.

**Comment by mholt** [comment]
@lucaslorentz Sorry for my delay -- I will get back to this thread soon! Currently focused on getting ACMEv2 support finished.

**Comment by tobya** [comment]
Hi @lucaslorentz - Sorry for being really stupid here, but can you explain to me the difference between this plugin and `on startup` ?  Does your plugin simply provide more control by having lots of sub directives that can be used?  How often does it run the  command?  Every request?  On first request?  On Startup?  

I feel like I'm missing a crucial piece of information about this plugin?  If I'm missing it perhaps others would benefit from a more succinct explanation also.

**Comment by francislavoie** [comment]
@tobya `on startup` just runs a simple command. `run` here acts like a simple process manager, and actually watches what is run and can reboot it, etc. Think a simple supervisord embedded in Caddy.

**Comment by lucaslorentz** [comment]
Thanks @francislavoie , I can't describe it better.

@tobya
Maybe we can merge `on` and `run` directive. I don't think the `on` keyword sounds good for always running background processes, but we could do something like:
```
on always dotnet ./MyApplication.dll {
    env ASPNETCORE_URLS=http://localhost:5000
    dir "C:\MyApplicationFolder"
    redirect_stdout stdout
    redirect_stderr stderr
    replicas 3
}
```

**Comment by francislavoie** [comment]
FWIW I don't think `on` and `run` should be combined, they're really two separate ideas, as you said yourself earlier. `on` is event handling, `run` is a process manager. I think `run` might be too simple of a name to really describe its functionality in the context of a Caddyfile, which might be part of the issue here. Maybe something like `run_proc`? I like that `run` is simple and short, but idk 🤷‍♂️

**Comment by tobya** [comment]
When does it run?

I think  `run` is not a great name either, though I'm not sure what is!

**Comment by mholt** [comment]
@lucaslorentz If you merge the latest master in again, I'll merge this PR.

Thanks for writing this plugin. My hope is that someone with enough interest will take it and build a full server type out of it, which is, IMO, the best solution to the problem this HTTP directive solves. I think this is on the edge of the scope of an HTTP server, if not totally outside it, so while useful, I would still rather see this as its own server type (cf. the forum post I linked to above). :)

**Comment by francislavoie** [comment]
To followup on Matt's comment, this is what he's talking about: https://caddy.community/t/brainstorming-a-caddy-server-type-for-processes-commands/2184?u=matt

**Comment by lucaslorentz** [comment]
I'm considering renaming the plugin to `supervise` or `supervisor`.
@francislavoie @tobya What do you think

And also create a `supervisor` server type. It would be a combo, httpplugin + servertype from same repository.

**Comment by mholt** [comment]
@lucaslorentz 👍💯 I like "supervise" for a directive name, and "supervisor" for a server type.

> And also create a supervisor server type.

This would be _fabulous_. I will be happy to help answer questions as you go. Do you want an invite to our Slack channel?

> It would be a combo, httpplugin + servertype from same repository.

I don't recommend this: it makes versioning on the build server difficult, and you'd have to release new versions of both in combo with each other. I would recommend keeping each plugin in its own repository.

**Comment by lucaslorentz** [comment]
@mholt 
I'm planning to share the supervisor logic and directive parsing.
I imagine both as complementary plugins, that should evolve together with same features.
On that case, do you think it's better 3 separate repositories?
Or keep it on the same repository?

**Comment by lucaslorentz** [comment]
@mholt 
I did a quick win implementation, reusing the same logic I had, same options.
https://github.com/lucaslorentz/caddy-run/pull/3

Check readme and examples:
https://github.com/lucaslorentz/caddy-run/blob/supervisor/README.md
https://github.com/lucaslorentz/caddy-run/tree/supervisor/examples

If you agree with it, I will rename this PR to `supervisor`. I think it's nice to have same name for servertype and directive, avoids mistakes.

**Comment by mholt** [comment]
Great work! Thanks Lucas, it'll go out with the next release of Caddy, at which point you can publish the HTTP server plugin.

However, you can publish the server type plugin any time (including now).

**Comment by lucaslorentz** [comment]
@mholt 
I'm facing an issue when I try to register the servertype plugin.

developerportalerror

Can you help me with that?

**Comment by mholt** [comment]
Oh, that's an attractive error message. 🤔  

Sorry about that! Deploys are currently broken because of Cloudflare activating 1.1.1.1 (I know, it's bizarre). I should have it fixed this week -- been busy with the end of semester classwork and such.

**Comment by lucaslorentz** [comment]
@mholt 
I still can't register the plugin, same error as before.
Any updates on that?

**Comment by mholt** [comment]
I don't get it. The log says `fork/exec /usr/bin/git: no such file or directory` but I KNOW the git command is DEFINITELY there. It works a split second earlier on a different function. It's very sporadic. I don't know what causes it... still looking into it...

**Comment by lucaslorentz** [comment]
@mholt 
Sorry, but I'm still not able to register the plugin on caddy website.
This is the repo: https://github.com/lucaslorentz/caddy-supervisor
It contains 2 plugins, httpplugin and servertype. I chose to share the repository between both plugins because they share a lot of code.

See below the errors I get:

Package Import Path: github.com/lucaslorentz/caddy-supervisor/httpplugin
Clone Url: https://github.com/lucaslorentz/caddy-supervisor.git
Version: v0.1.0
Error:
```
getting plugin list: pulling latest: exit status 1: >>>>>>>>>>>>>>> You are not currently on a branch. Please specify which branch you want to merge with. See git-pull(1) for details. git pull <remote> <branch> <<<<<<<<<<<<<<<
OK
```

Package Import Path: github.com/lucaslorentz/caddy-supervisor/servertype
Clone Url: https://github.com/lucaslorentz/caddy-supervisor.git
Version: v0.1.0
Error:
```
getting plugin list: pulling latest: exit status 1: >>>>>>>>>>>>>>> You are not currently on a branch. Please specify which branch you want to merge with. See git-pull(1) for details. git pull <remote> <branch> <<<<<<<<<<<<<<<
```

And using origin/master I get this error: https://github.com/mholt/caddy/pull/2061#issuecomment-379713000

Do you advise creating a new repository or something like that? I suppose since `Jun 16, 2018` other plugins was successfully registered. So it seems to be an issue with my repository.

**Comment by tobya** [comment]
@mholt  This is one for you I think.

**Comment by mholt** [comment]
@lucaslorentz  I would advise against putting two plugins in one repo unless they are always versioned together.

I kind of hate how fickle git can be sometimes... this is annoying because when I SSH into the server and do `git pull` (the same command the build server is running) in the same directory it works fine.

I'm rebooting the server now after clearing the cache, so hopefully that'll help? Try again in a few minutes...

**Comment by mholt** [comment]
@lucaslorentz I think I've narrowed it down to this fancy loop that registers directives, it's breaking the static analyzer: https://github.com/lucaslorentz/caddy-supervisor/blob/master/servertype/setup.go#L32-L33

But I will see if I can make it evaluate the string variable...

**Comment by lucaslorentz** [comment]
Don't worry about that.
Glad you narrowed it down.
I will replace the loop by multiple calls to registerDirective and will try again.

**Comment by mholt** [comment]
@lucaslorentz Actually I'm just uploading a fix which ignores loops like that for now. If a plugin name isn't hard-coded, it'll be skipped. (It looks like you won't be registering all those separately anyways, since they come as part of your server type.)

**Comment by lucaslorentz** [comment]
@mholt 
Great, thank you for spending time on it.
It's for sure an exception, no one else is doing loops like that to register directives.

**Comment by mholt** [comment]
@lucaslorentz It's rebooting; go ahead and try it again in a few minutes.

**Comment by lucaslorentz** [comment]
@mholt 
Almost worked.
I got to the next page. It correctly identified both plugins.
But then it fails to save with this error again:
```
getting plugin list: pulling latest: exit status 1: >>>>>>>>>>>>>>> You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

 <<<<<<<<<<<<<<<
```

**Comment by mholt** [comment]
@lucaslorentz That was a _great_ tip, I was able to reproduce the bug and I think it's fixed now. Using git fetch + git reset instead of git pull. The server is rebooting; go ahead and try it after a few minutes and let me know!

**Comment by lucaslorentz** [comment]
@mholt  Good job!
Both registrations worked!
I will wait deploy/build notifications now.
Thank you!

**Comment by lucaslorentz** [comment]
@mholt 
Just FYI. Both deploy/build went fine.

**Pull request merged**
