### PR TITLE
Add expires directive

### PR DESCRIPTION
**Pull request by hlidotbe**
See https://github.com/caddyserver/caddyserver.com/pull/78

### CODE REVIEW

**Comment by elcore** [comment]
LGTM 👍

**Comment by mholt** [comment]
So, Expires is just a header -- why does it need a separate plugin to do this? Why not just the `header` directive?

**Comment by elcore** [comment]
"It allows you to set different expiration durations depending on a matching regular expression." -- @hlidotbe 

> So, Expires is just a header -- why does it need a separate plugin to do this? Why not just the `header` directive?

**Comment by hlidotbe** [comment]
@mholt because the expiration date is relative to the request time. It is to avoid the browser fetching static (and supposedly unchanging) assets. 

It is a simpler version of the expires modules of nginx and Apache (will extend it as time allows but already fit basic needs) 

I'm on mobile but I think there was an issue about the same need.

**Comment by hlidotbe** [comment]
Redirect don't need expiration header no. I guess it could be moved closer to header to be more logical. I'll update the PR.

That being said, redirection should be moved much higher above rewrite (or rewrites lower), see #1107. In this case it has no influence though.

**Comment by mholt** [comment]
Thanks! You'll just want to add it to the [build server](https://github.com/caddyserver/buildsrv/blob/master/features/registry.go) and then we can get it out with the next release.

**Pull request merged**
