### PR TITLE
cmd: support running as a service for esp under windows

### PR DESCRIPTION
**Pull request by kardianos**
Without explicit support, you cannot run Caddy under windows as a service. On windows there is no "nohup cmd &".  Installing and running Caddy as a service is a simple as "caddy -service install && caddy -service start" on any operating system, including windows, linux, and osx.

This does not preclude others from packaging caddy using other methods.

### CODE REVIEW

**Comment by kardianos** [comment]
This PR works with systemd to make "service Caddy reload" reload the configuration.

**Comment by alexandreteles** [comment]
I liked this PR :+1: for it, I think that some tests should be made, but the fact that it works with "reload" on systemd and upstart is very good. Thank you! Let's wait for @mholt review.

**Comment by mholt** [comment]
I'll get around to it very soon :) Been really busy the last few days! Sorry for the wait.

**Comment by kardianos** [comment]
I still need to modify upstart to support the "reload", but it shouldn't be hard to do and is independent of these changes (need to add support in service package). No issue on the delay. Let me know if it looks like an acceptable approach and I'll look at the CLA.

**Comment by mholt** [comment]
I'm wondering if installing a program as a service is best left up to a separate process rather than bundling it into caddy. In other words, it feels strange to me to run caddy to "install" it then again to start it.

But the simplicity of this is quite alluring. Could you write up some specific docs as they might appear on the [CLI page](https://caddyserver.com/docs/cli) of the documentation? I want to understand this better and get more eyes on this before we build it into Caddy, if we do at all. So I'm not making a guarantee yet until I can put some more thought into this.

Phew, sorry. I had no idea that this HTTPS stuff would be taking so long.

**Comment by mholt** [comment]
What are the consequences of not supporting Caddy's reload right now?

**Comment by kardianos** [comment]
Under systemd, reload appears to work. Not supporting reload just means you run "service Caddy restart" (which won't be graceful) rather than "service Caddy reload".

**Comment by kardianos** [comment]
(Sorry, I haven't gotten to modifying the CLI docs or other docs. I'll get to it soon(tm).

**Comment by mholt** [comment]
I'm going to close this PR, perhaps prematurely, but not because I'm opposed to this change -- I think it just needs more testing since it's potentially a pretty invasive change that people will be relying upon in their production environments.

I think it'll help me feel more comfortable, too, once I see some docs showing how it works. We should have at least a handful of users test the implementation for some time in dev and in production before this'll be ready to merge in, depending on their results.

So next steps, to continue this at your leisure: write up some basic end-user docs (can be in Markdown in a gist or issue or something) and we can try to find a half-dozen or so people at least to try it out. Thank you again, @kardianos!

**Pull request closed without merging**
