### PR TITLE
onevent/startupshutdown: run command once per server block

### PR DESCRIPTION
**Pull request by elcore**
### 1. What does this change do, exactly?

Execute onevent commands once per server block

### 2. Please link to the relevant issues.

#1933 

### 3. Which documentation changes (if any) need to be made because of this PR?

n/a

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by elcore** [comment]
> This seems fine. I pulled and built it and it seems to fix the issue. I guess we might eventually get on events that should be executed for each host, but perhaps we can wait until that happens before worry about it.

👍

**Comment by tobya** [comment]
I'm not sure if this is related, but i get odd log entries .  Here is the log I tested 

https://gist.github.com/tobya/6254f1fd406994cc3f8621d339f26f06

If you take a look you'll see interspersed in my .bat batch file that runs on shutdown is startup log lines, these come from caddy not from my script.  The script I have just writes the date to a file.

**Comment by mholt** [comment]
Don't batch scripts print their commands as they're executed? `@ECHO off` or something is needed? (I haven't programmed .bat in like 10 years...)

**Comment by elcore** [comment]
> I'm not sure if this is related, but i get odd log entries . Here is the log I tested

I do not think this is related, `REM Should run once` sounds like an issue with your batch script

Reference: `error on 'on-fa727352-e277-49bf-b980-6771e9c37a00' hook`

**Comment by tobya** [comment]
No sorry its a bit confusing, the issue is not that my bat script is echoing nonsense (it doesnt do anything its just a test) its that caddy is for somereason putting the startup message in the output as though the on startup scripts are being run again.

> 2017/10/22 22:18:50 [INFO] Nonblocking Command "d:\php7\php-cgi.exe -b 49209" with ID e3bb5110-d7cb-42a9-b5b0-2ebbebd6a578

**Comment by elcore** [comment]
`2017/10/22 22:18:50 [INFO] Nonblocking Command "d:\php7\php-cgi.exe -b 49209" with ID e3bb5110-d7cb-42a9-b5b0-2ebbebd6a578` is the normal log output

https://github.com/mholt/caddy/blob/e5d04f9a96c3beb74f350688feba0d5003a22bea/onevent/hook/hook.go#L31

> Caddy is for somereason putting the startup message in the output as though the on startup scripts are being run again.

I am not familiar with Windows batch scripts, Caddy logs the message before its execution. Have you tried `@ECHO off` as suggested by @mholt

**Comment by tobya** [comment]
I tracked it, nothing to do with batch scripts or this change!  I'll take the discussion offline.

**Comment by elcore** [comment]
> I tracked it, nothing to do with batch scripts or this change! I'll take the discussion offline.

Great 😄. What was/is the issue

**Pull request merged**
