### PR TITLE
QUIC v43 (+v42 & v39)

### PR DESCRIPTION
**Pull request by Henrocker**
### 1. What does this change do, exactly?
Update QUIC to v43.

### 2. Please link to the relevant issues.
#2257 

### 3. Which documentation changes (if any) need to be made because of this PR?
None, just pushed Rel. 0.9.0 of quic-go and updated mint.
Additionally, **net/lex/httplex** became **net/http/httpguts**

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### 5. Example build

Check it out live [here](https://www.h-neef.de).

### CODE REVIEW

**Comment by mholt** [comment]
Unfortunately, updating QUIC is blocked on https://github.com/lucas-clemente/quic-go/issues/1353 -- the dependency is getting really quite heavyweight, which is contrary to the goals of the Caddy project. :(

Thanks for the PR, but this needs more discussion before diving in and doing it.

**Comment by Henrocker** [comment]
@mholt I would suggest to create a new branch for this caddy web server QUIC update. So everyone interested in the default QUIC version nowadays can pull the code from this branch of the original repo. 
Thanks!

**Comment by mholt** [comment]
@Henrocker Good idea. Made branch: https://github.com/mholt/caddy/tree/quic - have at it!

**Comment by AllenLi1990** [comment]
@mholt  I have encountered similar problems recently.chrome use v43 now.  i checkout your new branch "https://github.com/mholt/caddy/tree/quic".It seem like there is no new quic version on this branch.

**Comment by mholt** [comment]
@AllenLi1990 I only created the branch, I haven't updated QUIC, no time currently.

**Comment by Henrocker** [comment]
@AllenLi1990 git clone -b quic-43 --single-branch https://github.com/henrocker/caddy.git caddy

**Comment by AllenLi1990** [comment]
@mholt Got it~~
@Henrocker thanks~

**Comment by halfrost** [comment]
@Henrocker I build quic-43 branch, but encounter some error

```
./replacer.go:429:20: undefined: caddytls.GetSupportedProtocolName
./replacer.go:439:20: undefined: caddytls.GetSupportedCipherName
```

i see GetSupportedProtocolName()、GetSupportedCipherName() in caddytls/config.go, but i dont't know why compile error. Could you help me ? Thanks~

**Comment by Henrocker** [comment]
Please ensure, you use Go 1.10 or later for building.

**Comment by halfrost** [comment]
@Henrocker I use Go 1.11, maybe have a problem. I  will change to Go 1.10+ try again later.

**Comment by HuiiChong** [comment]
@halfrost I'm using Go 1.11, and success. You can try it by this [https://github.com/henrocker/caddy#build](url). And just replace its `caddy` to this.

**Comment by halfrost** [comment]
@HuiiChong Thanks~ I use Go 1.11 build success. I use `git clone -b quic-43 --single-branch https://github.com/henrocker/caddy.git caddy` this version build.

@Henrocker I use `git clone -b quic-43 --single-branch https://github.com/henrocker/caddy.git caddy`, build success,but when handshake,occurred some error.

image

chrome version 68.0.3440.106. Seemingly support QUIC v42, not v43 ?

**Comment by Henrocker** [comment]
Please see chrome://net-internals/#quic. There you can verify the supported version. Your version of chrome only supports Q043. 
If you like to build this version of caddy, first look at the https://github.com/henrocker/caddy#build Paragraph, as stated by @HuiiChong .

Then, into the mholt folder, replace the caddy folder with mine.

**Comment by Henrocker** [comment]
@halfrost You're welcome.

Consider having a look at PR #2288, that adds Q044, as well as cuts down the code, so that it actually shrinks the Codebase of caddy.

I've built it this way:

`go get github.com/mholt/caddy/caddy`, then `cd` into your $GOPATH/src/github.com/mholt/caddy, run: `git fetch origin pull/2288/head:q044`, then `git checkout q044` and then build caddy. 

This is going to add a new local branch of caddy, including @marten-seemann 's PR, that can then be built.

**Pull request closed without merging**
