### PR TITLE
Add root option to fastcgi directive

### PR DESCRIPTION
**Pull request by mwpastore**
Here is an awkward attempt at an implementation of feature request #1336. It appears to function correctly, but I'm guessing that the code quality and tests require more work, and/or I'm lacking some understanding that could lead to this breaking in some cases. Please let me know your feedback!

### CODE REVIEW

**Comment by abiosoft** [comment]
@mwpastore well, your _awkward_ attempt is actually a good attempt. Thanks 👍 

Have you tested this with actual containers ?

**Comment by mwpastore** [comment]
Thank you! Yes, I'm running it in production!

**Comment by mholt** [comment]
Great, will merge as soon as I have a chance to update the docs. If you get around to it first, feel free to submit a PR to https://github.com/caddyserver/caddyserver.com :)

**Comment by mwpastore** [comment]
I was going to ask if there's a separate repo for the web site. I'm on it!

**Comment by mholt** [comment]
Thanks! (I think AppVeyor was down, the tests passed.)

**Pull request merged**
