### PR TITLE
Preliminary test case for setup/config/ext.go

### PR DESCRIPTION
**Pull request by Karthic-Hackintosh**
Please review and let me know the changes

### CODE REVIEW

**Comment by mholt** [comment]
Cool, great start. Add a check to make sure those three extensions actually got added to the list, in that order. Then I think this can be merged in.

**Comment by Karthic-Hackintosh** [comment]
@mholt : Do i have to remove the assertions then ??

**Comment by mholt** [comment]
@Karthic-Hackintosh When you added the 3 checks for the extensions in the list, you removed the assertion that checks on the Next field (the one that calls sameNext). The ~2 lines that call sameNext and do that check should still be in your tests.

**Comment by mholt** [comment]
Looking great, thank you!

**Comment by Karthic-Hackintosh** [comment]
yep :)

**Pull request merged**
