### PR TITLE
add gopkg plugin

### PR DESCRIPTION
**Pull request by zikes**
### 1. What does this change do, exactly?

Adds the [gopkg plugin](https://github.com/zikes/gopkg) to Caddy.

### 2. Please link to the relevant issues.

NA

### 3. Which documentation changes (if any) need to be made because of this PR?

None necessary, however I can contribute to https://caddyserver.com/docs/http.gopkg if desired.

### 4. Checklist

- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
Hey @zikes, this plugin looks useful! I know we had some requests for this way early on (see #358).

I will catch up on Caddy PRs either this weekend or more likely next week (haven't been on the grid as much lately!)

**Comment by abiosoft** [comment]
Definitely useful. Now I can use fancy `go get` urls for my projects with ease.

**Comment by mholt** [comment]
Congrats, @zikes! Feel free to add your plugin to the Caddy website when the new version of Caddy is released.

**Comment by mholt** [comment]
@zikes You may now deploy your plugin to the Caddy website!

**Comment by zikes** [comment]
@mholt I tried to sign up on the developer portal a few hours ago with a couple of email addresses and neither has received the confirmation email yet.

**Comment by mholt** [comment]
@zikes Hmm, check your spam folder? We use Sendgrid. Make sure they're whitelisted... are you at qq.com?

**Comment by mholt** [comment]
@zikes I see your registrations, no errors reported in the logs... and I got a similar report today but it was because their (custom?) email server blocked the emails. Which account do you want to keep, I'll email you the activation link.

**Comment by zikes** [comment]
The @zikes.me one, thank you!

**Comment by mholt** [comment]
Ah! I found the problem. For some reason, when the server rebooted, the devportal didn't get the Sendgrid credentials like it should have. Emails should work in the future now. :)

**Pull request merged**
