### PR TITLE
confLoader: use import to handle globbed values for -conf flag

### PR DESCRIPTION
**Pull request by Whitestrake**
### 1. What does this change do, exactly?
Implements handling for glob values for the -conf flag.

### 2. Please link to the relevant issues.
https://github.com/mholt/caddy/issues/1910

### 3. Which documentation changes (if any) need to be made because of this PR?
https://caddyserver.com/docs/cli should be updated to mention the ability to use globs.

### 4. Checklist
- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

---
95% of the time spent preparing this pull request was figuring out how to fork, branch, then fix my branch, then rebase and start over, then squash two commits into one branch.

This proposed PR feels pretty hacky to me, but it works and I think the only alternative is to copy a whole lot of code out of `doImport` itself.

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for the change! Nice work.

This has a slightly different behavior than I would expect. If I have 3 separate Caddyfiles and one site defined in each, they may not have curly braces around them, and using import like this change does will cause that to break, because import merges them into a single Caddyfile.

What do you think we should do about this?

**Comment by francislavoie** [comment]
Do we have a good way built-in of determining if the `import`ed string begins with a label? If so then I think just artificially wrapping the rest with `{ }` when importing seems probably fine. It's undefined behavior otherwise, I'd think. The only case I can think of that this would break is if you for some reason in your root `Caddyfile` only have some directives without a label... which I don't think is valid outside of just specifying a couple directives in CLI, unless I'm mistaken.

**Comment by mholt** [comment]
> Do we have a good way built-in of determining if the imported string begins with a label?

In theory, an import statement where a site label is expected should be enough of an indicator whether the contents should contain a site label and thus have curly braces. But the hard part can be knowing where the label ends and the site definition starts. (Labels can span multiple lines, technically. Not my favorite design decision but oh well.)

I proposed this in #550 but I decided to decline it because it didn't seem popular.

**Comment by francislavoie** [comment]
Is there any actual downside to that? I think it's just worth doing, if someone can set it up.

Is there a way to access the list of valid directives (I guess including plugins' attributes)? If so then we could read until we find a directive.

Looking at the docs, it seems like the only valid way to have labels on multiple lines is with `,\h*\n` (comma + zero or more horizontal whitespace + newline), right? Then as soon as you find a newline without a comma, you know you're done with labels. :man_shrugging:

**Comment by mholt** [comment]
>  Then as soon as you find a newline without a comma, you know you're done with labels.

That's true, I think. Yeah.

**Comment by Whitestrake** [comment]
Not even the import docs themselves mention this caveat - honestly, I thought it would be implicit behaviour. Perhaps an update to the import docs and a pointer to those docs from the cli docs?

The implementation of this PR means that any kind of special handling of globbed files, such as reformatting flat Caddyfiles into braced site blocks, would have to be implemented in `caddyfile.doImport` instead.

**Comment by mholt** [comment]
@Whitestrake 

> The implementation of this PR means that any kind of special handling of globbed files, such as reformatting flat Caddyfiles into braced site blocks, would have to be implemented in caddyfile.doImport. Unless we want to handle things differently for -conf globs specifically?

Yes, if I'm reading you right. And that's how it currently works. Basically, we would need to update the docs to mention that the presence of a wildcard `*` performs a glob import under the hood as a convenience.

Fair enough? I think we can merge this.

**Comment by francislavoie** [comment]
@mholt is the sub-discussion we had here actionable? Should it be broken out into a separate issue?

**Comment by Whitestrake** [comment]
In my opinion, if there's agreement that this kind of automatic reformatting should be done, it should be handled in another issue/PR specifically aimed at modifying `doImport` which would affect the `import` directive as well as the `-conf` flag assuming this PR is merged.

**Comment by mholt** [comment]
I agree with @Whitestrake -- I think the sub-discussion here was interesting and probably more productive than what we had in #550 but let us handle that in a separate PR.

I'll merge this soon if we're all on the same page on it!

**Pull request merged**
