### PR TITLE
import the right version of quic-go

### PR DESCRIPTION
**Pull request by marten-seemann**
I have no idea how quic-go `v0.7.1-0.20190305092557-966b00dd3dc9` made it into the go mod file. quic-go [never even had a v0.7.1 release](https://github.com/lucas-clemente/quic-go/releases), and [commit 966b00dd3dc9](https://github.com/lucas-clemente/quic-go/tree/966b00dd3dc94caad6c3750bf8809a823d3d1036) doesn't have support for gQUIC.

We should use version [v0.10.1](https://github.com/lucas-clemente/quic-go/releases/tag/v0.10.1), which is the latest release from the gQUIC branch of quic-go.

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for catching this. I'm not sure how it got that version either; modules has been a mystery to me so far.

The build is failing on this version, though... (see CI results)

**Comment by marten-seemann** [comment]
814 errors 😱

But I see what's going wrong there. I'll need to cut a new quic-go release (of the gquic branch) that also uses go mod.

**Comment by mholt** [comment]
Thanks Marten. You're a champ! No hurry on that. We're definitely still in beta for a couple weeks _at least_.

**Comment by marten-seemann** [comment]
@mholt I had to make the gQUIC branch compatible with go mod first. Good news it, since I had to cut a new release anyway, I cherry-picked some fixes to the pacing algorithm from the main branch, which should speed up QUIC significantly.

**Pull request merged**
