### PR TITLE
Revert "*.txt, *.tpl, *.htm, *.html, *.md should always use eol=lf

### LINKED ISSUE #2348: dependency vendoring errors due to #2345
The changes introduced in #2345 (https://github.com/mholt/caddy/commit/d9e6e7ffa58bdd21cd9cef0d41802221a7b2fdc1) have caused issues when vendoring caddy in godep, and likely other tools.

In particular, the line endings in the following files show as changes, as soon as you clone the repo:
```
dist/CHANGES.txt
dist/README.txt
```

The error godep throws is this:
```
# cd /tmp/gopath.KZbghM/src/github.com/mholt/caddy; git checkout 2de495001514ed50eac2e09f474c32d417100c5c
error: Your local changes to the following files would be overwritten by checkout:
	dist/CHANGES.txt
	dist/README.txt
Please commit your changes or stash them before you switch branches.
Aborting
godep: error downloading dep (github.com/mholt/caddy/caddyfile): exit status 1
```

### PR DESCRIPTION
**Pull request by neolit123**
This reverts commit d9e6e7ffa58bdd21cd9cef0d41802221a7b2fdc1.

fixes #2348

@mholt @cblecker

### CODE REVIEW

**Comment by neolit123** [comment]
this PR only reverts the commit, but godep might also be confused for the other .gitattributes entries with `eol=XX`.

**Comment by neolit123** [comment]
cc @linquize

**Comment by mholt** [comment]
Hmm, is there a better fix that will not cause confusion? i.e. a way to solve one problem without causing another?

**Comment by cblecker** [comment]
@mholt https://github.com/mholt/caddy/pull/2351 may also fix it, as it appears it's just those three files with bad line endings.

**Comment by neolit123** [comment]
let's merge #2351 and close this one.

**Pull request closed without merging**
