### PR TITLE
Use environment variables for configuration

### LINKED ISSUE #304: How to use environment variables in a Caddyfile?
How do I use environment variables in a Caddyfile?

For example, say I am using the proxy directive, I want to be able to do the following:

```
proxy /api localhost:$API_PORT
```

### PR DESCRIPTION
**Pull request by mbanzon**
This fixes #304 - environment variables can be used in the `Caddyfile` with the `{$VAR_NAME}` syntax.

### CODE REVIEW

**Comment by mholt** [comment]
Cool. I think we don't want to do this in the parser, though. The [Replacer](https://github.com/mholt/caddy/blob/master/middleware/replacer.go) type is particularly good at this... it just that the replacement happens later.

Using the Replacer also gives each directive discretion over whether it wants to allow replacements on an argument. This may or may not be what the user would expect. The current PR forces the env var replacements right away for all tokens in the Caddyfile, but the Replacer would give the directives some control. I kind of like the idea of the latter.

**Comment by mbanzon** [comment]
As I read `Replacer` it is for replacing strings in transit during a request. I can't find anywhere that use `Replacer` for anything else - what am I missing?

**Comment by mholt** [comment]
Yeah, so far the Replacer is just used during requests. That's why I'm still not sure if it belongs in the Replacer, but I will have to think it over to make sure this really belongs in the parser.

**Comment by mbanzon** [comment]
fwiw I was looking for a place where the whole `Caddyfile` is present in one string as I initially wanted to do the replacement there. I see it as a short cut to get dynaic values into the configuration with no choice to the middleware/directives (I really have to re-state that I litterally just started using Caddy a week ago).

**Comment by abiosoft** [comment]
@mbanzon Hi, hope you're making progress.

**Comment by mbanzon** [comment]
@abiosoft still on a pause with this - want to see the deep thoughts of @mholt about where this environment use should be put in the code. So far the changes in this branch/PR works in my setup.

**Comment by mholt** [comment]
Yeah, my bad. It does feel weird to put that logic in the parser, but it also doesn't seem quite right to put it in the Replacer... will mull it over some more, look around the code for the best place.

**Comment by mbanzon** [comment]
When would the directives require control over the environment replacement?

**Comment by abiosoft** [comment]
If regex is the concern for it not to reside in the parser, it can be done without regex.

**Comment by mholt** [comment]
Okay, this doesn't belong in Replacer. Those are executed at request time and no need to slow down the request handling with such static values as env variables.

This is looking fine -- but it will need tests. Can you write some? :smiley:

**Comment by mbanzon** [comment]
Sure - I will look into it ;-)

**Comment by mbanzon** [comment]
Tests added - @mholt

**Comment by mbanzon** [comment]
I've made the changes we discussed. Regex is no longer used and it now supports the Windows `{%ENV_VAR%}` notation as well.

**Comment by mholt** [comment]
Thanks! Like a champ.

**Pull request merged**
