### PR TITLE
Set up CI with Azure Pipelines [skip ci]

### PR DESCRIPTION
**Pull request by mholt**
Very much WIP. I have no idea what I'm doing.

### CODE REVIEW

**Comment by thaJeztah** [comment]
```
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/d466a021-323d-4622-b377-6f20d771d97d.sh
golangci/golangci-lint crit uname_os_check 'MINGW64_NT-10.0' got converted to 'mingw64_nt-10.0' which is not a GOOS value. Please file bug at https://github.com/client9/shlib
/d/a/_temp/d466a021-323d-4622-b377-6f20d771d97d.sh: line 2: golangci-lint: command not found
##[error]Bash exited with code '127'.
```

Looks related to https://github.com/client9/shlib/issues/13

**Comment by thaJeztah** [comment]
(we were just discussing Azure Pipelines yesterday to investigate if it would be something for https://github.com/moby/moby, and noticed your work here 👍 😄)

**Comment by Mohammed90** [comment]
Honestly, Matt, the series of your commit messages here is a bit of comic relief 🤣 though I completely understand how frustrating it could be

**Comment by mholt** [comment]
:flushed: Ya'll are watching this? I'm embarrassed.

@thaJeztah Yep, that was a bummer of an issue, so I'm just using "go get" for now. Opened a separate issue here since I don't see why it can't just be fixed in the golangci-lint repo: https://github.com/golangci/golangci-lint/issues/472

Even though it has taken all afternoon, I'm... quite pleased with Azure Pipelines! Documentation is decent, but in general I still have no idea what I'm doing. :roll_eyes: 

Think I got it working. Am gonna merge and rip out AppVeyor and Travis. Azure Pipelines gives us tests on all 3 platforms, and it's _super fast_ in comparison to what I'm used to.

Might still want to add GitLab CI as a redundant CI system, but doesn't need to happen right now.

**Comment by Mohammed90** [comment]
I think running `golangci-lint` should be in a separate step than running the tests. Currently, if the lint fails but tests pass, then the entire step is marked as having passed. That is unless the `golangci-lint` is complementary and its failures are tolerated. What do you think?

**Comment by mholt** [comment]
@Mohammed90 I tried that, but with how flaky golangci-lint is right now, I think I want it to be optional until the install is rock-solid.

Gonna merge this now, but PRs welcome to make improvements!

**Comment by Mohammed90** [comment]
Can I create an issue to serve as a reminder to fix all the issues reported by `golangci-lint`? It should be good and easy for `good first issue` for newcomers.

**Comment by thaJeztah** [comment]
> 😳 Ya'll are watching this? I'm embarrassed.

haha, no worries! I think most developers can relate 👍

**Comment by mholt** [comment]
@Mohammed90 Yes, that would be great! I could tweet it then.

**Comment by Mohammed90** [comment]
@mholt done at #2541

**Comment by tullo** [comment]
CodeShip has Go 1.12 preinstalled - [Open source projects will always be free](https://codeship.com/pricing).

https://documentation.codeship.com/basic/languages-frameworks/go/

**Comment by elcore** [comment]
> 100 BUILDS/MONTH

@tullo I believe that's too low!

**Comment by tullo** [comment]
It might be enough if the [PR-only](https://blog.codeship.com/build-pull-requests/) trigger is used. OTOH I have not monitored the caddy project enough to know the actual build needs
@elcore

**Comment by divais** [comment]
@mholt Azure Pipelines gives us tests on all 3 platforms and a rich test reporting interface too. Suggest you publish the test results either using the Go task https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops#test or Publish test results @ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml

**Pull request merged**
