### PR TITLE
Correct browse modified date alignment

### PR DESCRIPTION
**Pull request by magikstm**
### 1. What does this change do, exactly?
Correct Browse "modified date" alignment that may be a bit misaligned depending on time and date.

I'm unsure if it is the best way to correct the issue.

### 2. Please link to the relevant issues.
#1952

### 3. Which documentation changes (if any) need to be made because of this PR?
None.

### 4. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by francislavoie** [comment]
In addition to my note in the review, I don't think this will still be perfectly aligned depending on the font. It'll need testing to see how it actually behaves.

**Comment by jungle-boogie** [comment]
I updated the issue that caused this PR with a, IMO, better solution.

**Comment by magikstm** [comment]
Thanks for the review. I could adjust. Please confirm which solution would be preferred (FrancisLavoie's suggestion or the suggestion in the PR).

**Comment by francislavoie** [comment]
@jungle-boogie my suggestion matches your first suggestion. I disagree with your 2nd one because it complicates localization using the JS Date API (unless you're willing to write up a solution that keeps that format but is still properly localized)

**Comment by magikstm** [comment]
@francislavoie I tested your suggestion locally on a Windows 7 x64 machine on IE11 (latest), Firefox (latest) and Chrome (latest) and it works reasonably well.

Current font which is "sans-serif" makes it not perfectly aligned, but I think it's quite usable.

**Comment by jungle-boogie** [comment]
@francislavoie, What's complicated about it? I'm not saying show the local date/time, just format it as per ISO8601.

**Comment by francislavoie** [comment]
@jungle-boogie Yeah, ISO8601 would be fine too. I was reading your example of `11-Nov-2017 01:04` which would require localization if using text for the month. I just think this solution is the easiest short-term without changing the date format.

**Comment by jungle-boogie** [comment]
Thanks for the reply, @francislavoie! Looking forward to this change.

**Comment by mholt** [comment]
Thanks everyone!

**Pull request merged**
