### PR TITLE
Test PR for CI Deploy

### PR DESCRIPTION
**Pull request by tobya**
Test PR to get CI Deploy working.

### CODE REVIEW

**Comment by mholt** [comment]
Oh, I need to look at this. Will try to do it ASAP. I need to set aside about two days, at this rate, to catch up with PRs :-/

**Comment by tobya** [comment]
No need to look at it yet, I'm still trying to get it all working.

Cant seem to get it to work with Travis-ci.  AppVeyor is fine, but I'll keep going.  Havent had a good run at it for a couple of weeks.

**Comment by francislavoie** [comment]
Still working on this @tobya? If not, we could close this until you get back to it.

**Comment by tobya** [comment]
Currently hibernating.

**Pull request closed without merging**
