### PR TITLE
Resolving lint notices

### PR DESCRIPTION
**Pull request by oddtazz**
Resolving lint notices.
Yay, my first commit :)

### CODE REVIEW

**Comment by mholt** [comment]
There are a couple/few lint warnings that can't be eliminated, unfortunately, because we must implement an interface defined by an external package, and that interface is not compliant with lint suggestions.

**Comment by mholt** [comment]
Did you know you can run `golint ./...` on your computer to see what the lint notices are?

**Comment by oddtazz** [comment]
I did try installing golint using `go get -u github.com/golang/lint/golint`
But I don't think it actually installed or maybe it didnt install in my default $PATH because I kept getting command not found.

**Comment by mholt** [comment]
I think being able to run `golint` (and `go test`) locally will save you a lot of time :wink: Check for where it is, make sure your $GOPATH/bin is in your $PATH, that might help!

**Comment by mholt** [comment]
Have you been able to look at this again @oddtazz ?

**Comment by oddtazz** [comment]
I'm afraid not. I tried looking at other stuff towards the end like you suggested.
`middleware\markdown\metadata\metadata_yaml.go:19:1: exported method YAMLMetadataParser.Init should have comment or be unexported`

`middleware\markdown\metadata\metadata_yaml.go:41:1: exported method YAMLMetadataParser.Markdown should have comment or be unexported`

But I couldn't figure out what it meant by ' should have comment or be unexported' so I kind of gave up.

**Comment by mholt** [comment]
Feel free to ask. :)

In Go, all exported identifiers (meaning they can be used by other packages) should have a godoc comment on the line above it. It's just a comment that starts with the identifier name and it describes what it is/does. It can be brief.

**Comment by wmark** [comment]
Re *golint*: It could be in your `$GOPATH/bin`. (Provided you have only one entry in `$GOPATH`, of course.)

**Comment by wmark** [comment]
Your indentation is off. `git diff` shows this with a red background:

git-diff

That said, setup your editor to run `go fmt` or `go imports` whenever you save a file. Or, run `go fmt -d` yourself before committing a change.

**Comment by mholt** [comment]
Hope this helped @oddtazz - any more questions?

**Comment by oddtazz** [comment]
Not really @mholt I didn't spend a lot of time on this after Mark told me it was rude of me to open this PR without RTFMing and searching the history first. I mean you are really awesome and helpful but I just want to learn how to code in go that's all. :)

**Comment by wmark** [comment]
???

**Comment by oddtazz** [comment]
`If you're new to open source development practices you will be forgiven, fear not. But, please, search through the issues, PR, and source code if you can before reporting. Chances are your issue has already been covered, or could be filed less boldly.` I really did not know what to do after this. Since I was told it's ok to take care of linting errors, but then it might not be the case. So I sort of stopped.

**Comment by wmark** [comment]
This does not apply to you. You are not opening a duplicate ticket or something like that.

**Comment by mholt** [comment]
I think that comment from gitter was about something else, about reporting a duplicate issue, not opening a PR to improve the code. 

We'd still very much like your help with lint fixes, @oddtazz. If you're no longer interested, feel free to close this PR. But that will make me sad since we'll have to ask someone else to help. 😞

**Comment by mholt** [comment]
Hey @oddtazz I'm going to close this PR because we're soon merging [lots of changes from the 0.9-wip branch](https://github.com/mholt/caddy/tree/0.9-wip) into master, and your changes will need to be synced up against master.

If you're interested, I'd be happy if you could fix the lint warnings after that branch is merged into master!

**Pull request closed without merging**
