### PR TITLE
[WIP] Add scgi middleware

### PR DESCRIPTION
**Pull request by sijad**
it's working, but because of poor experiences with buffers and IO's and programming I'm sure it can be more optimized specially `scgiclient`. it's based on `fastcgi` middleware.

## Need to be done

* [ ] Add copyright (it's based on fastcgi, so I'm not sure)
* [ ] Create test cases for `middleware/scgi/scgi.go`
* [ ] Create test cases for `middleware/scgi/scgiclient.go`
* [ ] Optimize/Rewrite `scgiclient.netString`

### CODE REVIEW

**Comment by mholt** [comment]
Nice start, I will have some feedback in the coming days!

**Comment by mholt** [comment]
Throwing this question out there: Would it be wise/possible to share the code in common between FastCGI and SCGI? In other words, maybe make a generic CGI interface?

Plain-old "regular" CGI has a [standard library package](https://golang.org/pkg/net/http/cgi/) that has a ServeHTTP method that does a lot of similar things -- maybe we could learn from its design as a pattern for our own "generic" CGI implementation and also for the details of its ServeHTTP method?

What do you think? More maintainable code in the long run, and less of it.

**Comment by sijad** [comment]
@mholt that's cool, but in this case where interface should be placed? in `middleware` folder or somewhere else?

**Comment by mholt** [comment]
Yeah, that sounds good. That package is for code that can be shared by any middleware.

**Comment by mholt** [comment]
How's it looking, to move the code around so that the code is shared between the two kinds of cgi packages? Do you think it will work?

**Comment by sijad** [comment]
@mholt sorry for delay, I didn't spend so much on this, I'll update you soon

**Comment by sijad** [comment]
Hi again, I'm so sorry for my delay
@mholt I really not sure how I can make this happened, can you please help me?

**Comment by abiosoft** [comment]
I'm actually struggling to spot the differences between this and fastcgi.

**Comment by mholt** [comment]
@abiosoft I haven't looked too closely at the differences but it looks like this scgiclient.go file is smaller than the fcgiclient.go file. Perhaps @sijad could enlighten us. :smile: I'm not particularly familiar with SCGI (or the internals of FCGI for that matter).

@sijad No worries, nice work so far. I'm not really sure at a detailed level either how that would look. I wouldn't make it a huge priority right now until the other items on your TODO list are complete (unless, of course, doing it will make those four items come together easier).

**Comment by sijad** [comment]
@mholt both of them are very similar, I'm trying to implement scgi server for go (you already mentions [this](https://bitbucket.org/mjl/scgi) in issue but it seems very old)

**Comment by mholt** [comment]
Hey @sijad, if you would still like to pick this up I would gladly welcome it! But master will soon be completely overhauled when [0.9-wip](https://github.com/mholt/caddy/tree/0.9-wip) is merged in, and your changes will need to be rebased.

I'll have a guide up soon on how to do it (not hard), but in the meantime, do you want to close this PR or just keep updating it?

**Comment by sijad** [comment]
close this PR. I'll help to complete this soon

**Comment by mholt** [comment]
Nice! Alright. Looking forward to it.

**Pull request closed without merging**
