### PR TITLE
Add Sec-Websocket-Protocol header to websocket preset.

### PR DESCRIPTION
**Pull request by ericdreeves**
As requested in #1170, this change adds the Sec-Websocket-Protocol header to the proxy directive's "websocket" preset. It also refactors the test.

### CODE REVIEW

**Comment by tehscorpion** [comment]
Seems like the build fails due to #1221. Lets wait until its merged.

**Comment by InAnimaTe** [comment]
See #1170 !! Really no need for this PR any longer.

**Comment by ericdreeves** [comment]
Per @InAnimaTe comments here and in #1170, closing this PR.

**Comment by mholt** [comment]
Thank you for addressing it anyway @ericdreeves !

**Pull request closed without merging**
