### PR TITLE
Rename directive requestid to request_id

### PR DESCRIPTION
**Pull request by tobya**
Following #1711 I caused confusion by using requestid and request_id.  I have changed all instances to request_id including the name of the folder.

Caddyfile now is like this

    request_id
    header /  "X-Request-Id" {request_id}

This is a breaking change for next release.

I will update documentation also https://github.com/caddyserver/website/pull/22

### CODE REVIEW

**Comment by elcore** [comment]
> Following #1711 I caused confusion by using requestid and request_id. I have changed all instances to request_id including the name of the folder

It's rather my fault, because I changed it to `requestid` (see below)  

__

Matt H. comment on your changes and I implemented it :) 

> Use a context key of "request_id" instead.

> Move this way higher in the chain (like, after "shutdown"), and I'm thinking about whether this should be renamed to "requestid".

**Comment by tobya** [comment]
It seems to work with the folder named requestid so unless there is a good reason to change it I think I would like to keep it consistent.

**Comment by elcore** [comment]
> It seems to work with the folder named requestid so unless there is a good reason to change it I think I would like to keep it consistent.

https://golang.org/doc/effective_go.html#names

"By convention, packages are given lower case, single-word names; there should be no need for underscores or mixedCaps."

**Comment by tobya** [comment]
ok, I'll update it.

**Comment by elcore** [comment]
I would like to know Matt's opinion

**Comment by mholt** [comment]
Let's keep the folder name `requestid` to match the package name, which should not have underscores in it. Thanks for checking!

**Comment by tobya** [comment]
OK.

I think that's it, I have changed the code to use `request_id` in both places.  Thanks to everyone for patience. Documentation will be done once I make changes suggested by matt.  https://github.com/caddyserver/website/pull/22

**Pull request merged**
