### PR TITLE
Fix for #854

### PR DESCRIPTION
**Pull request by abiosoft**
The bug was introduced in e2234497b79603388b58ba226abb157aa4aaf065

### CODE REVIEW

**Comment by abiosoft** [comment]
Pretty basic. Merging.

**Comment by kaihendry** [comment]
Just tested it after a `go get -u github.com/mholt/caddy` and it now works as expected!

Thank you!

Now it would be good if the Docker images updated with the fix. ;)

**Comment by abiosoft** [comment]
@mholt any release in sights ?

It'll make it to the docker image after the next release.

**Comment by mholt** [comment]
Seeing the fix, I think I might have caused this when I fixed a different bug in proxy related to headers.

So, thanks for finding this and making it right. :smile:

The next release is slated for Caddy 0.9, I'm working vigorously to get the beta versions out as soon as possible!

**Comment by kaihendry** [comment]
I was wondering if a test could be made for this?

Or is it too complex to run  another server to catch Host: in a test?

**Comment by mholt** [comment]
A test can definitely be written for this. It's on my list but I'd be happy to accept PRs on that!

**Comment by kaihendry** [comment]
I don't quite understand how testing works in Caddy. You recurse through directories running `go test`?
http://s.natalian.org/2016-06-01/1464743896_2548x1380.png

**Comment by mholt** [comment]
go test ./... gets all subdirectories too.

**Comment by kaihendry** [comment]
Cool. Didn't know about that syntax.
http://s.natalian.org/2016-06-01/1464745956_2548x1380.png

**Pull request merged**
