### PR TITLE
tls: suggestion - disable tls if port is http?

### PR DESCRIPTION
**Pull request by nemothekid**
This is more of a cosmetic thing, but when setting servers, we usually have times when we want to have a server listen on both on http and https without automatically upgrading to https. (Ex, our API service which if request over http, via XHR, doing a redirect to https would cause a CORS violation).

However, we also don't want to repeat options in our Caddy file. A configuration like this:

```
http://api.example.com, https://api.example.com {
	tls example.crt example.key
	bindaddr 0.0.0.0
	gzip
	log /dev/fd/1
}
```

Would cause a Caddy to error out with 
`Configuration error: Cannot multiplex 0.0.0.0:http (HTTP) and 0.0.0.0:http (HTTPS) on same address`

With the following change, tls won't be enabled for servers with port http (either `http://example.com` or `0.0.0.0:http`.

I think its a sane default (you don't usually want https on port 80), OTOH, I could understand if some people want to be paranoid about tls.  Lastly, you would be able override the tls check by doing something like `http://example.com:80` or `0.0.0.0:80`.

### CODE REVIEW

**Comment by mholt** [comment]
I've also experienced this issue, in fact, I have the exact problem right now with caddyserver.com.

My idea to handle this would have been to introduce a `use` directive that copies the config from another server, like:

```
http://api.example.com {
    gzip
    log access.log
}

https://api.example.com {
    tls cert.pem key.pem
    use http://api.example.com
}
```

So kind of like a same-file `import`. But again, simplicity is an important goal with Caddy and I think yours is better approach overall.

The only thing that concerns me about it is if a user does something like this:

```
http://mysite.com {
    tls certificate.crt server.key
}
```

In this case, the `tls` directive would be completely ignored. Obviously the user made a mistake but it goes out silently. Maybe a warning should be printed to the console? (See, for example, `root` does this if the site's root directory does not exist during server startup.)

**Comment by nemothekid** [comment]
So I looked into implementing the `use` directive, but from what I can understand (`parsing.go`?) there seems no way to do it in memory, and you would probably have to open the current caddy and extract the config from there. If we didn't want to change the parser too much I guess you could use the `import` directive and simply scan for the directive you want but that seems fragile (I don't yet understand the config parser too well).

Also looking to see how to cleanly implement the warning. So far only the parser is aware if a given block has multiple hosts and I don't think it makes much sense to put the warning in the parser.

**Comment by mholt** [comment]
In that case, let's just go with outputting a warning. Maybe in [tls.go](https://github.com/mholt/caddy/blob/33786408f0b1490ed20b867f123b6415312fae30/config/setup/tls.go) we could check `c.Port`, and if it equals "http" then we can raise a warning saying that TLS is not enabled for the plaintext HTTP port.

**Comment by nemothekid** [comment]
Added the warning -
```
Warning: TLS was disabled on host http://api.example.com. Make sure you are specifying https://api.example.com in your config (if you haven't already). If you meant to serve tls on port 80, specify port 80 in your config (http://api.example.com:80).
```

**Comment by mholt** [comment]
Yes! Perfect. Thanks.

**Pull request merged**
