### PR TITLE
Push to Go 1.8 :)

### PR DESCRIPTION
**Pull request by elcore**
Finally 😄 🍰

### CODE REVIEW

**Comment by wendigo** [comment]
Damn, you were first 🥇

**Comment by wendigo** [comment]
LGTM!

**Comment by wendigo** [comment]
@elcore Please adjust README.md accordingly: Note: You will need **[Go 1.7](https://golang.org/dl/)** or newer.

**Comment by elcore** [comment]
> @elcore Please adjust README.md accordingly: Note: You will need Go 1.7 or newer.

Sure 😄

**Comment by mholt** [comment]
Sorry, I already made the change before I saw this.

**Pull request closed without merging**
