### PR TITLE
Adding note on the rationale for Go 1.6

### PR DESCRIPTION
**Pull request by kennwhite**

### CODE REVIEW

**Comment by captncraig** [comment]
Maybe I'm being pendantic, but I feel being this specific might miss the point. We use 1.6 because we like being on the latest version and 1.6 finally regained the performance lost from 1.4 to 1.5. It is only "required" because of the tls stuff, but even without that, we would build with 1.6.

**Comment by mholt** [comment]
You're right Craig; I think this change is good though (at least, for now, later this year it'll be 1.7 and we'll probably update the parenthesized text) -- it denotes why we prefer the latest version.

**Comment by kennwhite** [comment]
Not a super big deal either way, but the /x/net/http2 merge to stdlib is a major change that many might not be aware of. There are many shops that have longer support timelines in prod, and this just sends a friendly signal that there's a considered rationale for it, not "upgrade to latest/greatest or buzz off" vibe that many OSS projects use.

**Comment by mholt** [comment]
Thanks Kenn!

**Pull request merged**
