### PR TITLE
Added breadcrumb map function to browse

### PR DESCRIPTION
**Pull request by tboerger**
In order to being able to really build a custom template for the browse
directive I have added another function to build even custom breadcrumb
paths. The other function `LinkedPath` is not that easy styleable as
this map function. That way we are able to build the breadcrumb path
matching different CSS frameworks like Bootstrap.

An example implementation should look like that, matching the Bootstrap structure:

```
<ol class="breadcrumb">
  {{range $url, $name := .BreadcrumbMap}}
    <li><a href="{{$url}}">{{$name}}</a></li>
  {{end}}
</ol>
```

Signed-off-by: Thomas Boerger <thomas@webhippie.de>

### CODE REVIEW

**Comment by mholt** [comment]
Cool. I think the name is a bit misleading though: LinkedList is actually a map :wink: What about `Breadcrumb` or something?

**Comment by tboerger** [comment]
Yeah sure, I just took this name because of the function LinkedPath

**Comment by mholt** [comment]
I'll merge this in, thanks again Thomas!

If you have a chance sometime, it'd be great to see a test for BreadcrumbMap. Maybe it'd even be possible to replace LinkedList with BreadcrumbMap? I'd love it if you could look into that, because I think the map is a better idea than the linked list, which is less flexible.

**Comment by mholt** [comment]
Errrr, that's weird, I definitely saw all 3 checks pass.

**Pull request merged**
