### PR TITLE
proxy: capitalize some request headers

### PR DESCRIPTION
**Pull request by tw4452852**
Go std lib will [normalize](https://github.com/golang/go/blob/master/src/net/textproto/reader.go#L600) the request header, so something like `Sec-WebSocket-Key` will be changed to `Sec-Websocket-Key`. while some servers (e.g. weechat in issue #1332) may depend on the original one case-sensitive.

Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

**Comment by joelnb** [comment]
I've tested your branch and I can confirm this fixes issue #1332 for me completely. Thanks for your work on this!

**Comment by mholt** [comment]
Umm, wait a sec. I'm not saying No to this PR, but WeeChat is broken if it treats headers as case-sensitive. Why should we fix something in Caddy that is not broken?

(Thanks for working on this @tw4452852! I'm not criticizing your fix, I'm upset at weechat.)

**Comment by tw4452852** [comment]
@mholt Maybe [weechat shouldn't treats headers as case-sensitive](https://github.com/weechat/weechat/blob/master/src/plugins/relay/relay-websocket.c#L153).
But I actually find [something similar in gorilla](https://github.com/gorilla/websocket/blob/master/client.go#L221).

**Comment by mholt** [comment]
Gorilla caved... I'm torn on this. I'll have to think about it!

**Comment by mholt** [comment]
Thanks for your thorough research on this @tw4452852 -- I've opened an issue upstream. I'll leave this open for a little bit but I will probably close it. If this change is what causes weechat to work with Caddy, then it's a bug in weechat and not in Caddy.

**Comment by mholt** [comment]
It looks like they're working on it upstream! 🙌  I'm going to close this now, since it looks like weechat 1.7 will have the fix. Thank you for your work on it!

**Comment by tobya** [comment]
Interesting.  While I can understand @mholt point of view and I agree with it, I also think it is not a good idea for caddy to modify headers as they go through.  

My understanding here is that caddy is modifying the headers on the request.

Should we allow @tw4452852 fix and also have weechat fix their side?

**Comment by mholt** [comment]
> My understanding here is that caddy is modifying the headers as the request is sent downstream.

The standard library is -- they are being normalized according to convention. Caddy itself doesn't change them, per-se. In HTTP/2, header field names are lowercased anyway. Let's just let weechat fix their end, and if Go shouldn't be modifying the casing of header fields, then that should be an issue with the Go standard library.

**Pull request closed without merging**
