### PR TITLE
caddytls: gofmt

### PR DESCRIPTION
**Pull request by elcore**
### 1. What does this change do, exactly?

gofmt `caddytls/handshake.go`

### 2. Please link to the relevant issues.

n/a

### 3. Which documentation changes (if any) need to be made because of this PR?

n/a

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by elcore** [comment]
Merge after the release of Go 1.11

**Comment by mholt** [comment]
So, wait, if `gofmt` itself changed, why doesn't it break Travis?

**Comment by elcore** [comment]
> So, wait, if gofmt itself changed, why doesn't it break Travis?

Travis is using Go 1.11beta2, that's the reason our builds broke in the first place.

I used `go1.11beta2 fmt ./...` to fix it (see our Slack)

**Comment by mholt** [comment]
Thank you!!

**Pull request merged**
