### PR TITLE
Use authentification credentials from proxy's configuration as a defa…

### PR DESCRIPTION
**Pull request by vchimishuk**
Implemented next feature request.
https://github.com/mholt/caddy/issues/933

### CODE REVIEW

**Comment by mholt** [comment]
Alright, this looks pretty good!

Can you write a test to check this? Then we'll be ready to merge it in. :smile:

**Comment by vchimishuk** [comment]
@mholt, sure. Will do.

**Comment by vchimishuk** [comment]
Amended commit with test changes.

**Comment by mholt** [comment]
Thanks @vchimishuk! Nice work. :) Mind if I make you a collaborator? This way you can [participate more in the project](https://github.com/mholt/caddy/blob/master/CONTRIBUTING.md) by reviewing pull requests and being able to create branches on this repo rather than having to fork it.

**Comment by vchimishuk** [comment]
It would be great. Thanks.

**Pull request merged**
