### PR TITLE
"sed" middleware for modifying a response by replacing one specified string by another

### PR DESCRIPTION
**Pull request by brk0v**
Replace strings in responses in runtime. 
Useful for rewriting page content for fixing https mixed content (rewrite schema) and http2 purposes (make single domain and preventing domain sharding).

**Examples**

In line:
```
# replace Ruby -> Go
sed / Ruby Go
```

And for several replacements:
```
sed / {
    # http -> https
    http://example.com https://example.com  

    # Ruby -> Go
    ruby go
}
```
 
**Notes**
  * Works only for ```text/html``` content type;
  * buffer size hardcoded to 256KB; 
  * works with/without gzip middleware.

### CODE REVIEW

**Comment by mholt** [comment]
Interesting - thabks for your work on this! I do have a few comments but am mobile right now, and it's hard to comment in-line on mobile. Stay tuned for more comments this week.

I have just a couple questions to start off.

1. Why is this middleware using a gzip reader? Ideally only the gzip middlewares should be aware of gzipping.
2. If this is to be merged in, it will need tests. We're trying to catch up on those now and don't want to fall further behind. Tests should assert baseline functionality and handle edge cases too. This is my fault as I haven't updated the contributors guidelines yet to reflect this requirement.

**Comment by mholt** [comment]
@brk0v I know I said I was going to comment more -- but I guess I should have clarified that I would wait until you responded, to avoid confusion. :smile: Would you like any help getting started with tests for this?

**Comment by brk0v** [comment]
@mholt Sorry for silence – had busy weeks. 

1. We can get gzipped responses from backend.
2. Agree with you – I'll write tests. 

Thank you for your willingness to help, but this version of code is not final. I've already found and fixed some issues. I going to commit changes (with tests) on this weekend.

**Comment by j-mcnally** [comment]
Not to be negative, because I love the contribution but is this something we really need / want in core? It seems like a very narrow use-case, most people I think would rather fix the files than have servers patch them. I think this would be a great candidate for pluggable middleware or a 3rd party extension once those stories get fleshed out a bit.

**Comment by mholt** [comment]
The tests are looking pretty good :+1:

@j-mcnally I can imagine a scenario where a backend is not in the site owner's control, but I do agree that this could also be used as a band-aid where minor surgery is required.

@brk0v I still like the idea of this. Can we rename the directive (and the entire middleware) to 'replace'? Mainly because it is not actually *sed* and I don't want users to get the wrong idea. The word 'replace' is also more intuitive for what it does.

Your PR comes at a unique time in Caddy's development, since I think we're starting to realize that its capabilities are going to outgrow a single repository and code base. I'm drafting up plans to make Caddy available with custom builds, able to use middleware other than what is built-in. This will allow us to continue to grow Caddy without growing its code base for all users. Still not 100% decided on this, but we're working on it.

If it's OK, I'm going to hold out acting on this for now - we can leave this open and I will update you when we've made some progress.

**Comment by mholt** [comment]
@brk0v Good news - it's time to move forward with this.

1. Can we rename the directive to `replace`?
2. Will you please [submit a PR to caddyserver/buildsrv](https://github.com/caddyserver/buildsrv/pulls)? This will be the first trial run of our new pluggable middleware system. The instructions for registering middlewares are in [that repository's CONTRIBUTING.md file](https://github.com/caddyserver/buildsrv/blob/master/CONTRIBUTING.md).

You will need to move the middleware to its own package which contains a Setup function, then of course, the handler itself. See [hello-caddy](https://github.com/abiosoft/hello-caddy) for a template you can paste your middleware into. You can use [caddydev](https://github.com/caddyserver/caddydev) to try it out.

**Comment by mholt** [comment]
This guide may help: https://github.com/mholt/caddy/wiki/Extending-Caddy

Let me/us know if anything is unclear - we'll get it fixed up!

**Comment by bigtan** [comment]
Actually, I was looking for this. I tried to make inverse proxy for google.com and the response from google.com has some content under the domain `ssl.gstatic.com` which is not available in my country(you know where am I now). So please consider continue this development, or make it configurable as a third part plugin.

Tanks for everyone.

**Comment by mholt** [comment]
@bigtan Ah, that's a very compelling use case. So what you're saying is that you could use this feature to strip content that would otherwise make the page blocked by your country. I think this would be a very valuable feature available with Caddy. @brk0v Let me know if you have any questions about this going forward.

**Comment by mholt** [comment]
@brk0v Is this something you'd like to do? If you're busy, I can find somebody else to help finish it up.

**Comment by mholt** [comment]
A lot has changed in the last 6 months; so I'm going to close this PR now, even though I still think this would make a neat add-on. Anyone else is welcome to pick this up! I've tagged as deferred so we don't forget about it.

**Comment by mholt** [comment]
This is effectively implemented with the filter plugin: https://caddyserver.com/docs/filter

**Pull request closed without merging**
