### PR TITLE
Log error when BasicAuth fails

### PR DESCRIPTION
**Pull request by tobya**
### 1. What does this change do, exactly?
Raises an error which is logged when a basicauth attempt fails.

The error logged is 

 > BasicAuth: user \"%s\" was not found or password was incorrect. {remote} {host} {uri} {proto}

which comes out as 

  >  18/Jan/2019:20:07:10 +0000 [ERROR 401 /admin] BasicAuth: user "admin" was not found or password was incorrect. 127.0.0.1 salmon.kinchik.ie /admin?withinfo=alskjfd HTTP/1.1

I updated the tests that when the error is raised they check it is the correct error.
### 2. Please link to the relevant issues.

#2402 

### 3. Which documentation changes (if any) need to be made because of this PR?
It could be added that BasicAuth will log an error when authentication fails

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by tobya** [comment]
I  noticed there are some unneeded lines etc and some tidying up, I will do that now.

**Comment by mholt** [comment]
Thanks Toby! Looking forward to reviewing this when I have a chance.

Always gotta be extra careful in the basicauth middleware...

**Comment by sumnerboy12** [comment]
Hi - I am testing this on v2.0 and I am not seeing any additional logging when BasicAuth fails. Looking at the code in https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/caddyauth/basicauth.go I can't the extra logging added in this PR.

Was this an intentional regression or something that was missed? I am trying to configure fail2ban on my reverse proxies but keep getting false positives due to the initial 401 sent when first trying to authenticate.

Sorry to re-open an old PR!

**Comment by mholt** [comment]
We rewrote the auth modules in v2, so it's not a "regression" per-se, as we have all-new logging facilities and logic in v2. We can add more logging in v2, but please open a new issue to request it. Thanks!

**Comment by sumnerboy12** [comment]
added #3363

**Pull request merged**
