### PR TITLE
Rollback changes creating an additional instance_startup event in #2161

### PR DESCRIPTION
**Pull request by tobya**
### 1. What does this change do, exactly?

When fixing #2161 by moving the emitEvent call to ensure on startup was called at the right point, a new event was created instance_startup.  After discussion it has been decided we dont need this new event and it was a breaking change so it has been reverted.

## Testing

- [ ] Can someone please test that this works on linux.  I have a windows only. 
- [ ] Can someone on linux please check that whatever is supposed to happen after SIGUSR1 still happens? 
- [x]  see if it fixes the issue with caddy not executing `on startup` if caddy.service was included.  __Tested and Works__

 - Anyone else who would like to test. 

### 2. Please link to the relevant issues.

#2161 

https://github.com/hacdias/caddy-service/issues/21

### 3. Which documentation changes (if any) need to be made because of this PR?

none

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
Looking at this more, I would actually like to see these events related to startup/shutdown:

- `launch` - The Caddy process has been launched
- `startup` - A Caddy instance has been started
- `shutdown` - A Caddy instance has been shut down
- `exit` - The Caddy process is exiting cleanly

@tobya Will that be sufficient for your needs? And this way it doesn't have to be a breaking change.

**Comment by elcore** [comment]
> `launch` - The Caddy process has been launched

Using `caddy.StartupEvent` will not work (Slack comments)

**Comment by mholt** [comment]
Why won't it work? I don't understand -- explain exactly what is needed.

**Comment by tobya** [comment]
@elcore I never quite understood why moving the call to emitEvent solved the issue with hook.service. What is the timing that was preventing the startup event from firing in the main caddy code?

**Comment by tobya** [comment]
@mholt I think the idea of creating new events is a good one.  However what elcore says is correct, the way the code is at the moment the launch event (if it gets called in the same place as  caddy.Startupevent will never run anything in the caddyfile.  

I presume this event is used for something else other than the caddyfile event.

Maybe we should leave any additional changes until after the next release.

**Pull request merged**
