### PR TITLE
dep

### PR DESCRIPTION
**Pull request by tgulacsi**
Use the new dep package management tool to manage dependencies and the vendor/ directory.

### CODE REVIEW

**Comment by tgulacsi** [comment]
Sorry, plugins haven't been intended to be pushed here. Just the dep'd dependencies.

**Comment by tobya** [comment]
Thanks for the PR. We would need some more justification to take a PR this large. Perhaps you could provide a bit more explanation

**Comment by mholt** [comment]
It seems like Go is not necessarily settling on dep either. https://research.swtch.com/vgo-intro

Right now we don't have a compelling reason to switch from using the vendor folder with gvt. Thanks for your PR though! Feel free to continue discussion, but I'm going to close this.

**Comment by tgulacsi** [comment]
Understood.

Matt Holt <notifications@github.com> ezt írta (időpont: 2018. febr. 21.,
Sze, 20:40):

**Pull request closed without merging**
