### PR TITLE
Implement sorting for "browse"

### PR DESCRIPTION
**Pull request by pyed**
now you can click on `Name`, `Size` or `Modified` to sort the listing

### CODE REVIEW

**Comment by mholt** [comment]
Cool, thanks for working on this. Normally I'm not opposed to several commits, but this PR has many small ones, so if you could squish them together, that'd be good. Use git rebase -i - [here's a guide if needed](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

**Comment by holizz** [comment]
What's the rationale for leaving the list unsorted by default? Wouldn't it be more useful if the listing was sorted by name by default?

**Comment by mholt** [comment]
@holizz Is it not already sorted by name by default for you?

**Comment by holizz** [comment]
@mholt Nope.

Apparently [File.ReadDir()](https://golang.org/pkg/os/#File.Readdir) returns its values "in directory order". And [according to StackExchange](http://unix.stackexchange.com/questions/13451/what-is-the-directory-order-of-files-in-a-directory-used-by-ls-u) "directory order" depends on which filesystem you're using.

Using btrfs and I can easily reproduce it by running "touch 3 2 1" which causes caddy to display the files in reverse-alphabetical order. But if I run "rm 1 2 3 && touch 1 2 3" it displays them in alphabetical order. If I try that experiment on ext4 it always display them in reverse-alphabetical order.

**Comment by mholt** [comment]
Okay. I had seen that and wondered if it was FS-dependent. Thanks for your experiments.

@pyed How about we default by name ascending order (with the arrow in the template) - so that and squashing the commits should do the trick. :+1:

**Comment by pyed** [comment]
@mholt now it defaults to sorting by name in ascending order, should be good to go

**Pull request merged**
