### PR TITLE
Use naoina/toml for MIT license. Make proxy_test work in any directory.

### PR DESCRIPTION
**Pull request by ijt**

### CODE REVIEW

**Comment by mholt** [comment]
Thanks Isaac! I know this is a really simple change but any chance you could sign the CLA? (It's standard.)

**Comment by ijt** [comment]
Sure Matt, I'm in transit but can do it sometime in the next day.

**Comment by ijt** [comment]
Okay, done.

**Comment by abiosoft** [comment]
Interesting to see that both toml packages are identical and the only change required is the import path.

**Comment by abiosoft** [comment]
Still not signed. 😕 
Could it be you committed with a different email address ?

**Comment by mholt** [comment]
Hmm, CLA assistant is maybe bugging again, I do see @ijt in the list when I go look it up, so it was signed. Thank you!

**Comment by ijt** [comment]
Yay, thanks!

**Pull request merged**
