### PR TITLE
Close idle connections after graceful shutdown timeout

### LINKED ISSUE #809: Change in proxy config not reflected by in-process restart (http2 keep-alive connection not closed)
#### 1. What version of Caddy are you running (`caddy -version`)?
master

#### 2. What are you trying to do?
Reload Caddyfile with new proxy setting with USR1 using in-process restart.

#### 3. What is your entire Caddyfile?
Before:

```text
www.example.com (domain must be served on https, e.g. let's encrypt)

proxy / www.google.com {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
}
```

After:

```text
www.example.com

proxy / www.yahoo.com {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy

#### 5. What did you expect to see?
After `kill -USR1` on caddy pid, should show error page of Yahoo instead of Google.

#### 6. What did you see instead (give full error messages and/or log)?
Still showing error page of Google.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
1. Start caddy with Caddyfile proxying Google
2. Change Caddyfile to proxy Yahoo
3. kill -USR1 CADDY_PID
4. Observe caddy still proxying Google

### PR DESCRIPTION
**Pull request by tpng**
Since the related changes in Go stdlib (https://github.com/golang/go/issues/9478, https://github.com/golang/go/issues/14204) is pushed back to Go 1.8 (ETA 2017 Feb), I think it is good time to make this change in Caddy as 0.9 is merged in master.

Closes  #809.

### CODE REVIEW

**Comment by mholt** [comment]
Interesting -- if this works, I like it: simple and minimal. It probably deserves a comment with a link to that issue.

Does this actually work though? I've never tried setting the ConnState function when trying to _stop_ the server, I have only set it before starting the server. (Are there any race conditions of concern?)

**Comment by tpng** [comment]
These are the related issues:
https://github.com/golang/go/issues/9478 
https://github.com/golang/go/issues/14204

I have tested before with Chrome and the idle connections are closed with ConnState set inside Stop().
It is racey in nature though, net/http checking ConnState is nil and calling it vs setting it on Caddy side.

**Comment by tpng** [comment]
To avoid the race we need to setup ConnState before calling Serve() and check if we are shutting down in the ConnState hook, if yes then we close the idle connections.

For the shutdown check, I think we can set s.listener to nil inside Stop() after calling Close() and check it inside ConnState.

Something like:
```go
// NewServer creates a new Server instance that will listen on addr
// and will serve the sites configured in group.
func NewServer(addr string, group []*SiteConfig) (*Server, error) {
	s := &Server{
		Server: &http.Server{
			Addr: addr,
			// TODO: Make these values configurable?
			// ReadTimeout:    2 * time.Minute,
			// WriteTimeout:   2 * time.Minute,
			// MaxHeaderBytes: 1 << 16,
		},
		vhosts:      newVHostTrie(),
		sites:       group,
		connTimeout: GracefulTimeout,
	}
	s.Server.Handler = s // this is weird, but whatever
	s.Server.ConnState = func(c net.Conn, cs http.ConnState) {
		if cs == http.StateIdle {
			s.listenerMu.Lock()
			// server closed, reap idle connection
			if s.listener == nil {
				c.Close()
			}
			s.listenerMu.Unlock()
		}
	}

	// codes after
}

// Stop stops s gracefully (or forcefully after timeout) and
// closes its listener.
func (s *Server) Stop() (err error) {
	// codes before

	// Close the listener now; this stops the server without delay
	s.listenerMu.Lock()
	if s.listener != nil {
		err = s.listener.Close()
	}
	s.listener = nil
	s.listenerMu.Unlock()

	// codes after
}

```

**Comment by mholt** [comment]
@tpng Ah, this is good! Thank you!! I'm going to merge it in so it will go out on the first beta version coming up.

**Comment by FiloSottile** [comment]
I'm a bit confused: no connection should transition to state Idle after a call to SetKeepAlivesEnabled.

**Comment by tpng** [comment]
keepAlives = true:
New -> Active -> Serve the request -> Idle -> New request on same connection -> Active -> ...
keepAlives = false:
New -> Active -> Serve the request -> Closed

From https://golang.org/pkg/net/http/#ConnState:

        // StateIdle represents a connection that has finished
        // handling a request and is in the keep-alive state, waiting
        // for a new request. Connections transition from StateIdle
        // to either StateActive or StateClosed.

**Comment by FiloSottile** [comment]
Yep, that's my same understanding. So in this PR, SetKeepAlivesEnabled is called first, making transitions to StateIdle impossible, and **then** listener is set to nil. So the if that fires on both StateIdle and listener == nil should be unreachable, no?

**Comment by tpng** [comment]
Currently, SetKeepAlivesEnabled only affect new connections to the server (https://github.com/golang/go/issues/9478), which is why this PR is required in the first place.
That if block is for connections we opened before closing the listener.

**Comment by FiloSottile** [comment]
Ah, ok, that would make sense. But my understanding was that SetKeepAlivesEnabled also affects existing connections that transitioned to StateActive in the meantime.

StateActive -> StateIdle -> SetKeepAlivesEnabled(false) -> StateActive -> StateClosed (not StateIdle)

I guess I'm looking at the source to confirm.

**Comment by FiloSottile** [comment]
SetKeepAlivesEnabled changes the doKeepAlives return value, which is used in writeHeader for every request. So I think I'm correct saying that SetKeepAlivesEnabled affects all future *requests*, not connections, and after a SetKeepAlivesEnabled(false) call there won't be any state transitions to StateIdle.

**Comment by tpng** [comment]
Now I remember why, it's because HTTP2 only keep one and only one persistent connection for all requests and is not affected by SetKeepAlivesEnabled.

**Comment by FiloSottile** [comment]
Ah, that makes sense, and TIL. There's golang/go#15386 that is related, but I can't find one about HTTP/2 not being affected by SetKeepAlivesEnabled. Is there any particular reason? Should we open one?

**Comment by tpng** [comment]
I believe https://github.com/golang/go/issues/9478 will fix this issue.

**Pull request merged**
