### PR TITLE
Proxy: Single WebSocket connection

### PR DESCRIPTION
**Pull request by nemothekid**
This PR depends on #984 because they would need to be merged and I didn't want to do that work.

The relevant commits to this PR are c4e65df and d534a21. 

How it essentially works is it created a new transport for Websockets connections (kind of wasteful), but then hijacks the connection on that transport and uses it to continue the websocket connection.

It passes the test created in #764, but I'm not sure if it actually fixes the problems outlined in #746.

### CODE REVIEW

**Comment by edrex** [comment]
I can confirm that quassel-webserver, which uses socket.io, is working behind Caddy with this change. Nice!

**Comment by mholt** [comment]
Wow, nice work!! The "wasteful" code you refer to is only executed on WebSocket requests, so it would hardly impact performance I think in normal proxy scenarios.

**Comment by mholt** [comment]
This is looking pretty good to me. Thank you so much for solving a challenging problem! Should we go ahead and merge this in @nemothekid?

**Comment by nemothekid** [comment]
Ok, I'll merge it in when we agree on #984 (I have to merge that into this, then update the branch).

**Pull request merged**
