### PR TITLE
Partially fix raw IP request regression (#2356)

### PR DESCRIPTION
**Pull request by Zenexer**
### 1. What does this change do, exactly?

Partially resolves regression that resulted from a security patch, as described in #2356

### 2. Please link to the relevant issues.

#2356

### 3. Which documentation changes (if any) need to be made because of this PR?

This still needs to be discussed.

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by Zenexer** [comment]
I did my best to minimize the potential for unintended side effects.  Initially, I tried to get it to intelligently fall back to the most likely intended certificate under certain circumstances, but the changes were too disruptive, and I couldn't easily gauge the fallout.

**Comment by jung-kurt** [comment]
Nice work, @Zenexer. Thanks for your prompt attention to this issue. Your solution addresses some subtleties that I would have certainly missed. My simple example and my more complicated working setup both work properly with your changes.

**Comment by lukenowak** [comment]
Thank you @Zenexer , I checked your PR code and it works perfectly on my quite complex configuration (a lot of sites with many name-based certificates and few endpoints with IP based -- IPv4, IPv6 and others).

For the ip access I have caddyfile like:
```
https:[::1]:5555, https:127.0.0.1:5555 {
  bind 127.0.0.1
  tls ip.crt ip.key
}
```

And my cert has two IPs in altSubjectName with meaningless common name. All works well.

Of course! If at least one entry for IP-based access has wrong certificate, like adding to my Caddyfile:

```
https:[::1]:5555/cous, https:127.0.0.1:5555/cous {
  bind 127.0.0.1
  tls other.crt other.key
}
```

all endpoints returns error.

This is expected, as it is said in the docs, that all configurations shall share exactly the same TLS stanzas. Improving error reporting in this case is subject to another thing I think.

**Comment by mholt** [comment]
Mostly superseded by https://github.com/mholt/caddy/commit/a7aeb979be5a59ae82fac0783fe54b83c7fc57fd - but I would like to at least merge in your tests, @Zenexer, either here or CertMagic, wherever they belong.

**Pull request closed without merging**
