### PR TITLE
Add webdav directive

### PR DESCRIPTION
**Pull request by hacdias**
Add `webdav` directive for webdav plugin! 😄

### CODE REVIEW

**Comment by mholt** [comment]
@hacdias The new version is out, so you can update this on the Caddy website now.

**Comment by hacdias** [comment]
Thank you Matt!

**Comment by Rurik19** [comment]
Hi ! @hacdias - my issue will work now?
https://github.com/hacdias/caddy-webdav/issues/1

**Comment by hacdias** [comment]
I think so 😄

**Comment by Rurik19** [comment]
@hacdias  it seems that it doesn't work. i get 
```
ip - - [28/Jul/2017:12:50:43 +0500] "OPTIONS / HTTP/1.1" 404 14
```
in log

**Pull request merged**
