### PR TITLE
Strip [] from IPv6 addresses for FastCGI.

### LINKED ISSUE #845: PHP REMOTE_ADDR coming in as `[::1]` instead of `::1`.
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.2

#### 2. What are you trying to do?
Run Symfony

#### 3. What is your entire Caddyfile?
```text
http://shop-front.localhost:8000
root /Volumes/Code/shop-front/web
gzip

rewrite {
  to {path} {path}/ /app_dev.php?{query}
}

fastcgi / 127.0.0.1:9000 php {
  index app_dev.php
}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy`. I'm using php70 and caddy from homebrew on OS X 10.11.

#### 5. What did you expect to see?
`$_SERVER['REMOTE_ADDR']` in PHP should be `'::1'`.

#### 6. What did you see instead (give full error messages and/or log)?
`$_SERVER['REMOTE_ADDR']` in PHP is `'[::1]'`

### PR DESCRIPTION
**Pull request by nesl247**
Fixes #845.

### CODE REVIEW

**Comment by mholt** [comment]
And there we have it! Looks good, thanks @nesl247!

**Comment by nesl247** [comment]
Thanks @mholt. Surprised to have it accepted. Was figuring on a rejection due to not using regex to do it in one go or something.

**Comment by mholt** [comment]
Ugh, please don't use regular expressions when this is so much simpler and faster. You did good. :+1: And thanks for updating the tests, I didn't realize the IPv6 format had to remove the brackets for CGI.

**Comment by mholt** [comment]
@nesl247 I've added you as a collaborator so you can help with future PRs and issues as you see fit, including the convenience of creating new branches in this repo to work on things.

Might be worth taking another quick gander at the [contributing guidelines](https://github.com/mholt/caddy/blob/master/CONTRIBUTING.md) to get an idea how we do things, basically submit a PR to let your changes be reviewed by other collaborators, and please feel free to help collaborate when you can!

**Comment by nesl247** [comment]
Will try and help out where I can, so thank you.

**Pull request merged**
