### PR TITLE
Basicauth: Use Caddy-Rewrite-Original-URI header

### PR DESCRIPTION
**Pull request by elcore**
Is this better @mholt ?

### CODE REVIEW

**Comment by mholt** [comment]
But the question is, is this what the user intends? If they do a rewrite, maybe they're doing the rewrite so that it matches the URI accepted by basicauth...

**Comment by elcore** [comment]
> But the question is, is this what the user intends? If they do a rewrite, maybe they're doing the rewrite so that it matches the URI accepted by basicauth...

I don't know! I thought of that too, but I don't know any case where it might be applied to.

**Comment by mholt** [comment]
I think we just have to decide one way or the other what the semantics of 'rewrite' are. For now, rewrite is a change to the URI as if the original request had been to the rewritten URI in the first place; having basicauth ignore that as an exception doesn't seem like a good idea at this point. But again, thank you so much for jumping in and contributing! I think we would need a lot more discussion on this if we were to make a change though.

**Comment by elcore** [comment]
>  I think we just have to decide one way or the other what the semantics of 'rewrite' are. For now, rewrite is a change to the URI as if the original request had been to the rewritten URI in the first place; having basicauth ignore that as an exception doesn't seem like a good idea at this point. But again, thank you so much for jumping in and contributing! I think we would need a lot more discussion on this if we were to make a change though.

No problem :smile: --  I want to be a partner for you and for the community!  An active member of the community! The guy who cares about Caddy!

**Pull request closed without merging**
