### PR TITLE
Update markdown middleware

### PR DESCRIPTION
**Pull request by MrH100000**
Issue #794 

Changed markdown.go and metadata.go to allow objects in front matter.
Tests will fail due to JSON front matter. The unexpected EOF is from the static generator throwing an error from the JSON front matter in the test file json.md

### CODE REVIEW

**Comment by mholt** [comment]
@abiosoft made a good point that we should probably tread carefully between this PR and #762. It's likely that the other PR will be merged first, and then this one will have to be synced up. (Sorry. Hope that's okay.)

**Comment by MrH100000** [comment]
Thats fine. I'll re-write my fix after it's merged.

**Comment by mholt** [comment]
@MrH100000 Okay, feel free to sync up and continue; the other markdown PR has been merged.

**Comment by mholt** [comment]
@MrH100000 Also I really like the tests for this. Any plans or questions about finishing this up?

**Comment by MrH100000** [comment]
I've been getting my computer repaired, probably in a couple of days to a week, depending on when my computer is fixed.

**Comment by mholt** [comment]
@MrH100000 How's your computer doing? :smile:

Just FYI some major changes are going to hit the master branch soon from the [0.9-wip branch](https://github.com/mholt/caddy/tree/0.9-wip) and your PR will need to be synced up. I will be working on a guide to explain how middleware works with the new changes soon. But I will close this PR for now.

I do hope we will still see your changes make it into Caddy! :+1: Just open a new PR when you're ready to submit them against the new code.

**Comment by MrH100000** [comment]
All good as of now, os had to be reinstalled so I'll have to rewrite my changes.

**Comment by mholt** [comment]
Haha, yay for getting the computer fixed! Sorry about your data loss 😞 

Feel free to copy what you can from this PR. Looking forward to it!

**Comment by MrH100000** [comment]
Okay, I'll get started on that.

**Comment by MrH100000** [comment]
Does #762 fix JSON parsing so it can parse objects?

**Comment by mholt** [comment]
I don't think so, but CC'ing @weingart anyway.

**Comment by weingart** [comment]
It does not, but it should not error out, but simply ignore the extra content.  I question the use of parsing deeply nested objects...

**Pull request closed without merging**
