### PR TITLE
Rewrite improvements

### PR DESCRIPTION
**Pull request by abiosoft**
### New features
`r` or `regexp` is now optional.

#### 1. Conditions
Syntax: 
```
if a cond b
``` 
* `a` and `b` are strings with support for [placeholders](https://caddyserver.com/docs/placeholders)
* `cond` is one of `is`(equality), `not`(inequality), `has`(has substring), `starts_with`(has prefix), `ends_with`(has suffix) and `match` (matches regexp).
* There can be multiple lines.

Examples
```
if {path} is /error
if {path} not /static
if {>User-Agent} has Android
if {path} starts_with /static
if {path} ends_with .html
# for match, regexp is on the right
if {file} match error_.*\.html
```
#### 2. Multiple rewrite destinations
`to` now accepts multiple values. 

Syntax
```
to dest [...dest]
```
First successful destination or the last one will be used.

From 
```
to {uri} {uri}/ index.php?_uri={uri} 
```
* An attempt will be made for `{uri}` as a file. It is used if file exists.
* Otherwise, an attempt will be made for `{uri}/` as a directory. It is used if directory exists.
* Otherwise, `index.php?_uri={uri}` will be used.

#### Examples
If user agent has Android in it, show mobile maintenance page if it exists or redirect to mobile path.
```
rewrite {
    if {>User-Agent} has Android
    to /mobile/maintenance.html /mobile/{uri}
}
```
If its not favicon.ico, attempt to server the file or directory, or forward the request to index.php.
```
rewrite {
    if {file} not favicon.ico
    to {uri} {uri}/ index.php?_url={uri}
}
```

### CODE REVIEW

**Comment by mholt** [comment]
And to clarify for the benefit of others reading this, from our chat on gitter, the multiple `if` lines are `and`ed together.

This looks amazing. Going to take a closer look soon!!

**Comment by pwFoo** [comment]
is it possible to check if a file exists like done with apache htaccess file?
```
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d

```
I'm not mean the syntax, just the feature ;)

**Comment by abiosoft** [comment]
No, not directly. `to` can be used to mimic that.

**Comment by pwFoo** [comment]
Hi @abiosoft could you give me an example how to rewrite the url only if the file not exists?

**Comment by abiosoft** [comment]
```
rewrite {
    to {uri} {uri}/ /the_new_url
}
```
This rewrites to `/the_new_url` if the file/directory does not exist. However, if it does exist, it will be served instead.

**Pull request merged**
