### PR TITLE
Add {user} placeholder to CommonLogFormat

### PR DESCRIPTION
**Pull request by magikstm**
### 1. What does this change do, exactly?
Make code in line with current documentation for CommonLogFormat for {user} placeholder.

I tested with latest version of the plugin https://github.com/tarent/loginsrv.

It works as noted in the documentation https://caddyserver.com/docs/log under the predefined format `{common} (default)`.

I've not added a new test yet.

### 2. Please link to the relevant issues.
#1951

### 3. Which documentation changes (if any) need to be made because of this PR?
None.

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by francislavoie** [comment]
I'm a bit confused. Where is `user` being set? As far as I can tell, it hasn't been put in yet.

**Comment by magikstm** [comment]
@francislavoie I believe it's not currently used in Caddy's core.

@Tobya mentioned he would add it soon for basicauth in #1543.

It may be used in plugins since #1937.

I added it in plugin http.login (https://caddyserver.com/docs/http.login) in https://github.com/tarent/loginsrv/issues/32.

**Comment by francislavoie** [comment]
Alright cool, thanks! So what happens if there's no value for `user` after this is merged? I figure it should default to `-` as before if nothing is set.

**Comment by magikstm** [comment]
@francislavoie If set by plugin or core it's `user`. If unset, it's `-`.

**Pull request merged**
