### PR TITLE
Cert issuer and subject string conversion fix.

### PR DESCRIPTION
**Pull request by laszlo-kiss**
The original code causes compilation failures:

```
server1|vagrant$ go get github.com/mholt/caddy/caddy
# github.com/mholt/caddy/caddyhttp/httpserver
src/github.com/mholt/caddy/caddyhttp/httpserver/replacer.go:464:22: cert.Issuer.String undefined (type pkix.Name has no field or method String)
src/github.com/mholt/caddy/caddyhttp/httpserver/replacer.go:476:23: cert.Subject.String undefined (type pkix.Name has no field or method String)

```

Used RawIssuer/RawSubject instead of missing .String() method.

### 1. What does this change do, exactly?
Fixes a compilation error due to missing method call (.String()). This method is not in the "pkix.Name" structure.

### 2. Please link to the relevant issues.
https://github.com/mholt/caddy/issues/2275#issue-353008788

### 3. Which documentation changes (if any) need to be made because of this PR?
None.

### 4. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
I think you need to be running Go 1.10. What version of Go are you using?

**Comment by laszlo-kiss** [comment]
I'm using 1.9 (I have two, my Mac (macOS High Sierra) and Linux (Mint) both fail. The build instructions probably need to change, it calls for 1.9.

**Comment by laszlo-kiss** [comment]
I see also that the 'fix' is not really a fix, since it fails the test. **Sorry about that.** I think we should drop this.

**Comment by francislavoie** [comment]
Okay @laszlo-kiss, closing per your request :smile:

**Pull request closed without merging**
