### PR TITLE
Extend tls client auth

### PR DESCRIPTION
**Pull request by wmark**

### CODE REVIEW

**Comment by mholt** [comment]
:+1: LGTM

**Comment by weingart** [comment]
I really think that the path parts should be pulled out as a separate commit.  As a lot of things will likely end up depending on the path being cleaned appropriately, why don't we pull that out and get it committed asap?

**Comment by mholt** [comment]
@weingart What's wrong with the commit as-is, exactly? The fix is still in the code base. Is it just because it's not clear from the commit message that the path change was made?

**Comment by weingart** [comment]
It just looked like it was two different things in one commit.

**Comment by mholt** [comment]
It was; granted, Mark could have opened two PRs, but for some reason cla-assistant is not allowing him to push to master :disappointed:

**Pull request merged**
