### PR TITLE
Allow replacement params in log filename

### PR DESCRIPTION
**Pull request by tobya**
I have the start of a PR for this issue #1396 

@mholt There are some comments inline if you have time to take a look.

Essentially I call replacer on the path for the log file.

If the logfile returned is differnt to the currently open one, I close it and open the new log file? I have questions around

- Am I closing the existing logfile correctly?
- Would a better approach be to leave a file open for each different log file opened rather than closing and reopening?
- Is this desired behaviour are we happy that this Issue is to be implemented?
- Is #1404 relevant to this at all?

This is not ready to merge yet, I need to add tests and tidy up some code but need some feedback on direction.

### CODE REVIEW

**Comment by tobya** [comment]
This needs to be merged with #1246 before it can work.  I will merge it and repush

**Comment by mholt** [comment]
Hey, sorry, I will get to this. Just working through a backlog.

**Comment by tobya** [comment]
Actually my fix here needs to be rewritten due to #1246 - I will try to get around to it or someone else can take my branch and modify.

**Comment by mholt** [comment]
Sounds good. Sorry about that!

**Comment by mholt** [comment]
Actually... I dunno, is this even thread-safe? It would need testing as well... I'm not sure opening and closing logs per-request is a good idea either.

**Comment by tobya** [comment]
I was concerned about that myself.  However it seems that the new logger.go  code ensures that a single logger per file is kept open.  If the code opens a log file if not open and then on each log request simply uses  the correct logger instance it might be valid (eg no need to close and reopen files).

Also the use of replacer would need to be restricted (eg {host} only).  

However while a nice to have I don't think this is an essential feature and certainly we can park it for the time being.  I might come back to it in a while if I can find an elegant solution.

**Comment by mholt** [comment]
@tobya Thanks, I also just thought of the security implications of this which I commented in the other issue. Sorry about that. But I think you're right, it's a lesser priority right now than other features/bugs that need to be worked out.

**Pull request closed without merging**
