### PR TITLE
Use proper Request

### PR DESCRIPTION
**Pull request by wendigo**
This PR is due to changes made in Golang's tip: https://github.com/golang/go/issues/17525

There's also one outstanding bug on golang's tip that I cannot track: reading from ping-pong WS proxy causes EOF
```
 go test ./...
--- FAIL: TestWebSocketReverseProxyFromWSClient (0.00s)
	proxy_test.go:205: EOF
FAIL
FAIL	github.com/mholt/caddy/caddyhttp/proxy	0.039s
```

**Please note:** this PR will PASS on golang 1.7.3 and fail on golang's tip.

### CODE REVIEW

**Comment by elcore** [comment]
> There's also one outstanding bug on golang's tip that I cannot track: reading from ping-pong WS proxy causes EOF

Me either :( I cannot find the source :( -- Anybody an idea?

**Comment by wendigo** [comment]
Updated travis & readme

**Comment by wendigo** [comment]
Before merging this PR I would like to resolve outstanding issue with WS proxy test. It's really weird and I can't track it down.

**Comment by wendigo** [comment]
Calling @mholt for help! 🙏

**Comment by mholt** [comment]
Hi! Sorry, I've been really busy with midterms this week. I'll come back to this ASAP, don't worry.  Really excited for this fix, so thank you very much. :) If anybody else can help you in the meantime, that might be faster! We have a number of collaborators now, so hopefully they can jump in like Elcore and Tw do.

**Comment by tw4452852** [comment]
I'm in!

**Comment by tw4452852** [comment]
Ah, the issue is introduced by [this commit](https://github.com/golang/go/commit/4859f6a416b053d57fcc9d8f43e81e9d218280e9) and I have uploaded [a fix](https://github.com/mholt/caddy/pull/1207). It should work now.

**Comment by mholt** [comment]
Excellent, thank you @wendigo!

I'll send you an invite to be a collaborator on the project. That'll give you push access to the repo so that you can submit changes in branches instead of having to fork the project. You can (and should) also help review pull requests when you can. :) Thank you for your contributions!

**Comment by wendigo** [comment]
Cool, thx for the trust @mholt :) Will do my best!

**Pull request merged**
