### PR TITLE
vendor: add gopkg.in/mcuadros/go-syslog.v2

### PR DESCRIPTION
**Pull request by elcore**
### 1. What does this change do, exactly?

Vendor gopkg.in/mcuadros/go-syslog.v2

### 2. Please link to the relevant issues.

#2057 

### 3. Which documentation changes (if any) need to be made because of this PR?

/

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
Thanks Eldin. We don't vendor test dependencies so that we can minimize the size of the repository. Test dependencies can quickly get out of control. They're not needed for successful builds and testing is the perfect opportunity to discover errors related to upstream dependencies as well.

**Comment by elcore** [comment]
> As much as I am not a fan of saving dependencies primarily due to large repo size. The chance of the repo owner (of one of the dependencies) deleting their project is a realistic possibility.

(Gophers Slack)

ping @abiosoft

**Comment by abiosoft** [comment]
:rofl: :rofl: :rofl: Like seriously @elcore 

Matt has a good point as well and I am fine with either.

**Comment by elcore** [comment]
> 🤣 🤣 🤣 Like seriously @elcore

Matt has a good point as well and I am fine with either.

Sorry, I just wanted to quote you!

**Comment by abiosoft** [comment]
Nothing serious, just kidding.

**Comment by mholt** [comment]
Haha, thanks everyone -- but I don't think we want to vendor test dependencies at this time. :)

**Pull request closed without merging**
