### PR TITLE
log: support multiple log entries under one path scope

### PR DESCRIPTION
**Pull request by tw4452852**
fix issue #1044

Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

**Comment by mholt** [comment]
Yay, this is great Tw! Loved the added test to ensure multiple entries are written.

Just a few lint warnings:

```
caddyhttp\log\log.go:66:6: exported type LogEntry should have comment or be unexported
caddyhttp\log\log.go:66:6: type name will be used as log.LogEntry by other packages, and that stutters; consider calling this Entry
caddyhttp\log\setup.go:83:2: can probably use "var rules []*Rule" instead
```

If you don't mind. :) And then we should merge this in.

**Comment by tw4452852** [comment]
@mholt . Have fixed these lint warnings.

**Comment by mholt** [comment]
Cool, thanks, but now the tests fail. :smile:

**Comment by tw4452852** [comment]
Oops...Sorry. Forget checking after rebase.

**Comment by mholt** [comment]
Great! Thank you so much again! I seriously don't know how anything would get done without your help (and others too, of course).

**Comment by tw4452852** [comment]
You're welcome :smile:

**Pull request merged**
