### PR TITLE
Fix for travis-ci

### PR DESCRIPTION
**Pull request by SmilingNavern**
Fix golang version, because build is failing with golang 1.11beta2

### CODE REVIEW

**Comment by SmilingNavern** [comment]
@mholt @elcore look please, i've fixed travis-ci :)

**Comment by SmilingNavern** [comment]
@elcore but go 1.11 wasn't released yet? So this fix can help with ci for now and after release of go 1.11 we can fix other problems?

**Comment by elcore** [comment]
> @elcore but go 1.11 wasn't released yet? So this fix can help with ci for now and after release of go 1.11 we can fix other problems?

No, it's not released. Matt should decide if we should merge this PR.

**Comment by SmilingNavern** [comment]
I think it's not actual anymore)

**Pull request closed without merging**
