### PR TITLE
Add reverse_proxy preset

### PR DESCRIPTION
**Pull request by dulldave**
Hey! First time contributor and caddy user for that matter.

Based on #851 I've added the `reverse_proxy` preset for the proxy directive and a couple of tests to go with it.

**Example**
```
localhost {
    proxy / localhost:8080 {
        reverse_proxy
    }
}
```

Instead of

```
localhost {
    proxy / localhost:8080 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
}
```

Looking forward to a code review

### CODE REVIEW

**Comment by mholt** [comment]
Hey @dulldave - thanks for your PR and congrats on your first one! :smile: I will look at this shortly.

**Comment by abiosoft** [comment]
LGTM

**Comment by mholt** [comment]
My only holdup would be the name, `reverse_proxy`. That's what the `proxy` directive is intended to be, so having a `reverse_proxy` keyword within it might be confusing. There's got to be a better way to describe this. Transparent, maybe?

**Comment by dulldave** [comment]
Yeah I could get behind `transparent` as the preset instead. I think that might actually make more sense.

**Comment by dulldave** [comment]
@mholt @abiosoft how's this instead? 😄

**Comment by mholt** [comment]
@dulldave This is great! Thanks, I'll merge it in now.

Congrats on your first PR. You did a great job, here's why:

- You tackled an open issue that was at your skill level
- You implemented a solution as discussed in the issue
- You were responsive to feedback and made changes accordingly
- The added tests are vital (and the table format is extensible)
- The logic is clean and well-structured

I'll give you commit rights to the repository so you can continue to contribute in the future as you please in a separate branch right in this repo, and to help review other pull requests, etc. Thank you!

**Comment by dulldave** [comment]
Thanks!

**Pull request merged**
