### PR TITLE
fixed data races in websockets

### PR DESCRIPTION
**Pull request by acmacalister**

### CODE REVIEW

**Comment by mholt** [comment]
Great work Austin :+1: I'm not merging anything (significant) into master for right now, since we're getting ready for letsencrypt to land. After that I'll revisit this -- won't be too long. Thanks!

**Comment by mholt** [comment]
Okay, we're ready to merge whenever you are. (Will wait for confirmation pending #306)

**Comment by acmacalister** [comment]
@mholt If I understood the comments right, I went ahead and added `TrimSpace` for each message to remove any possible line terminators at the end of a message. If I remember correctly the default behavior of Scan is read up to the newline character and that is where it breaks for line, which we then use to send a message.

**Comment by mholt** [comment]
LGTM. Thanks Austin!

**Pull request merged**
