### PR TITLE
caddy: move EmitEvent(InstanceStartupEvent, instance)

### PR DESCRIPTION
**Pull request by elcore**
### 1. What does this change do, exactly?

Move `EmitEvent(InstanceStartupEvent, instance)` to `caddy.Start()`

### 2. Please link to the relevant issues.

https://github.com/hacdias/caddy-service/issues/21

### 3. Which documentation changes (if any) need to be made because of this PR?

n/a

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by elcore** [comment]
I will close this PR. After some thought, I came to the conclusion that the plugin is responsible, as it is managing instances.

**Comment by mholt** [comment]
Hmm, I actually kind of like this change though.

**Comment by elcore** [comment]
> Hmm, I actually kind of like this change though.

Of course we can do it anyway, but I personally believe that the plugin should be responsible emitting these events.

**Comment by tobya** [comment]
@elcore What is the status on this?  Did we decide to merge it here or leave it to plugin authors.  Can we merge or close this PR?

**Comment by elcore** [comment]
We haven't decided on this

**Comment by Rubyj** [comment]
@elcore Just tested this fix using the service plugin. Can confirm it does not solve the issue with caddy not starting when using service plugin.

**Comment by mholt** [comment]
@elcore Can you do one more change for this PR? In `onevent/hook/config.go` we need to update `SupportedEvents`. We need to distinguish between instance startup and startup, and I think I want to use `snake_case` for `instance_startup` for its string representation.

**Comment by elcore** [comment]
> Can you do one more change for this PR? In onevent/hook/config.go we need to update SupportedEvents. We need to distinguish between instance startup and startup, and I think I want to use snake_case for instance_startup for its string representation.

I have implemented your suggestion, please keep in mind that this will change the behavior of this plugin, as `on startup` used to run on `caddy.InstanceStartupEvent`!

**Pull request merged**
