### PR TITLE
Add connect_timeout and read_timeout to fastcgi.

### PR DESCRIPTION
**Pull request by ericdreeves**
Hi,

Here's a summary of the changes for #1094 , as well as some questions/concerns.

### Connect Timeout

I added a new connect_timeout property to the fastcgi directive, e.g.:

	fastcgi / 127.0.0.1:9000 {
		connect_timeout 10s
	}

I can test the new property using docker-compose: use iptables on the proxy 
and drop packets that are outbound to the FastCGI service.

I'm having a hard time writing a test for it. I combed through the net
package to find some way to generate a i/o timeout but found nothing. Some
[tests](https://golang.org/src/net/timeout_test.go) in the net package use
internal packages-those appear to be the ones with which the connection can be
impeded.

Any suggestions on how to test this while continuing to use net.Dialer?

### Read Timeout

Similarly, here's the new read_timeout property:

	fastcgi / 127.0.0.1:9000 {
		read_timeout 10s
	}

I ended up assigning a deadline in streamReader.Read(), but had to use a
type assertion in order to assign the value. I *think* this is the right place,
or close, but I'm not so sure about the type assertion.

At any rate, feedback appreciated!

### CODE REVIEW

**Comment by ericdreeves** [comment]
I'll investigate this failure:

	--- FAIL: TestNumProcs (0.00s)
		automate_test.go:12: Expected numProcs to return max(NumCPU-1, 0) but got 2 (NumCPU=32)
	FAIL
	FAIL	github.com/mholt/caddy/dist	0.009s

**Comment by ericdreeves** [comment]
Regarding this failure:

	--- FAIL: TestNumProcs (0.00s)
	    automate_test.go:12: Expected numProcs to return max(NumCPU-1, 0) but got 2 (NumCPU=32)
	FAIL
	FAIL    github.com/mholt/caddy/dist 0.009s

Is it possible that this is due to a change in the Travis test environment? I cannot reproduce locally, and the AppVeyor build does not seem to generate the same failure.

**Comment by mholt** [comment]
It could very well be unrelated. I'll be willing to accept your PR despite that failing test. I'll have to look at that function again and see if there's something we can do to resolve it...

**Comment by wendigo** [comment]
Unfortunately as https://github.com/mholt/caddy/pull/1264 was merged you need to resolve conflicts in your branch before merging this change.

**Comment by ericdreeves** [comment]
Other than resolving the conflicts, is there anything else holding this back?

**Comment by mholt** [comment]
@ericdreeves Not from my side :) -- I'll approve once conflicts resolved!

**Pull request merged**
