### PR TITLE
Correct unused assignments

### PR DESCRIPTION
**Pull request by buddhamagnet**
https://github.com/mholt/caddy/issues/697

### CODE REVIEW

**Comment by randall2602** [comment]
Some of these are trying to check if a variable is true, perform an action, and then set the variable to false. The "set" part is in the if block so it falls out of scope and causes the unused assignment error. The corrections in this pull request just remove the "set" part but don't address that the variable value may need to be changed.

**Comment by buddhamagnet** [comment]
@randall2602 sorry my bad looking in more depth now.

**Comment by mholt** [comment]
@randall2602 I'm trying to figure out where that's an issue. Can you point me to a file / line number?

**Comment by randall2602** [comment]
@mholt 
middleware/commands.go line 116 sets "part" to "" if condition true
middleware/context.go line 156 sets inTag to false if condition true

both of these assignments happen within the if block so it makes sense why it's an issue. I'm curious though if the assignment is important even though it's not currently working.

**Comment by buddhamagnet** [comment]
@mholt @randall2602 yeah I can't see that either, the values I'm seeing are reset at the end of the functions and are not used/returned?

**Comment by mholt** [comment]
@randall2602 Both of those are in fact unnecessary, so removing them is okay. The one in context.go was there (I can say because I wrote it) because, technically, it keeps the state true. However, the tool is right, in that the assignment operation is useless. We can remove it safely; any modifications to the code should be covered by tests anyway.

I'm good with this. The failing CI on Travis is an unrelated on Go tip, so I'll merge this in. Thanks @buddhamagnet! :+1:

**Pull request merged**
