### PR TITLE
use log instead of fmt to obey the -log flag

### PR DESCRIPTION
**Pull request by tpng**

### CODE REVIEW

**Comment by mholt** [comment]
Actually, I want these to be displayed to the user at stdout, not in the logs. Especially the addresses that are currently being served.

**Comment by tpng** [comment]
Oh, that's ok then. What about the errors one?

**Comment by mholt** [comment]
Hmm, the errors one is fine I guess. Maybe change it to to:

```go
log.Printf("[WARNING] Unable to open error page '%s': %v", where, err)
```

and that should do it!

**Comment by tpng** [comment]
Pull request updated.

**Comment by mholt** [comment]
Thanks -- great catch!

**Pull request merged**
