### PR TITLE
allow consecutive spaces in the header

### PR DESCRIPTION
**Pull request by pyed**
https://github.com/mholt/caddy/issues/261#issuecomment-158415762

### CODE REVIEW

**Comment by mholt** [comment]
Ah, cool - thanks!

**Comment by hdid** [comment]
Thanks @pyed

**Comment by hdid** [comment]
same problem with new template (v 0.8.1)
@mholt

**Comment by mholt** [comment]
D'oh. Missed that one, but I fixed it locally. Changes will be pushed soon.

**Pull request merged**
