### PR TITLE
proxy: initialize ReverseProxy.Transport earlier and fix TCP connection leak

### PR DESCRIPTION
**Pull request by crvv**
### 1. What does this change do, exactly?
Fix a bug introduced in 98de336, #2070
https://github.com/mholt/caddy/commit/98de336a2130aa102e52af4d8150cb3c05101d15#diff-a71769529a289e215ba922059611256bL309

Before 98de336, `proxy` used `http.DefaultTransport` for every request.
After 98de336, `proxy` creates a new `http.Transport` for every request.
Then `caddy` will create a lot of TCP connections and won't reuse them.

I found this because `github.com/transmission/transmission` can only have 1024 file descriptors, And it encounters error `too many files open` frequently when I upgraded `caddy` to 0.10.13.

### 2. Please link to the relevant issues.
See 1.

### 3. Which documentation changes (if any) need to be made because of this PR?
None.

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by crvv** [comment]
CI failed because of
https://github.com/golang/go/issues/25048
https://github.com/golang/lint/issues/397

**Comment by mholt** [comment]
Re-running CI tests.

Pinging @tchaudhry91

**Comment by tchaudhry91** [comment]
Ah! Yes, this makes sense.
I can check the broken test also tomorrow morning. Unfortunately, do not have access to my dev system right now.

**Comment by crvv** [comment]
I am very glad to become a collaborator. Thanks.

**Pull request merged**
