### PR TITLE
proxy: set request's body to nil explicitly

### PR DESCRIPTION
**Pull request by tw4452852**
fix issue #1206

Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

**Comment by wendigo** [comment]
How did you find that?

**Comment by tw4452852** [comment]
Just bisect and find [this commit](https://github.com/golang/go/commit/4859f6a416b053d57fcc9d8f43e81e9d218280e9). It splits the returned body and content length. Before this commit, when content length is 0 && can't peek one byte from original body, the body will be set to nil. But now it will remain the original body. 
And for our case, the outgoing request is from a server request which its body is never nil:

```
// For server requests the Request Body is always non-nil
// but will return EOF immediately when no body is present.
// The Server will close the request body. The ServeHTTP
// Handler does not need to.
```

So we should reset its body to nil explicitly.

**Comment by wendigo** [comment]
Makes sense - thank you for clarification :) I've been trying to fix that using delve but it's a lot of code to go through...

**Comment by mholt** [comment]
Thank you Tw! :+1:

**Pull request merged**
