### PR TITLE
Add -restart=inproc flag for in process restart

### LINKED ISSUE #416: Create "Soft" restart mode
Currently, the graceful restarts fork the caddy process and the parent process exits. This causes trouble with certain process managers (supervisor and docker) to name a few, as they can't track the pid change (even if you argue they should.)

I would like to propose a "soft" reset mode.

Perhaps `-reset inProc` as opposed to the default of `-reset fork`.

It would stop all of the servers, apply configuration changes, and then restart servers. I realize it is not quite as seamless as the graceful restart mode. Existing connections will need to be dropped, and there may be some (very brief I hope) downtime before the re-bind takes effect. I am ok with that for the simpler management this can allow.

### PR DESCRIPTION
**Pull request by tpng**
Closes #416.

### CODE REVIEW

**Comment by mholt** [comment]
Woah, weird, the tests are failing on Travis with:

```
git clone https://go.googlesource.com/crypto /home/travis/gopath/src/golang.org/x/crypto
Cloning into '/home/travis/gopath/src/golang.org/x/crypto'...
remote: Daily bandwidth rate limit exceeded for IP 52.0.240.122.
fatal: protocol error: bad pack header
package golang.org/x/crypto/ocsp: exit status 128
```

This looks good otherwise. I'm gonna wait and see if I can trigger a rebuild to see if it works...

**Comment by tpng** [comment]
Yeah, seems like travis is being rate limited by googlesource, I can try to push a new version to trigger a rebuild.

**Comment by mholt** [comment]
@tpng No, I'm working on it now. I like one commit for small changes like this. :smile:

**Comment by mholt** [comment]
Hmm, it's not picking up on my fix. @tpng Could you rebase with master and squash your commits and push again? It should work then.

**Comment by tpng** [comment]
No problem, I will try again after UTC 0:00 to see if the limit reset.

**Comment by mholt** [comment]
@tpng You can do it now, I just pushed a fix to bypass rate limits. :+1:

**Comment by mholt** [comment]
Wow Travis:

```
$ openssl aes-256-cbc -K $encrypted_3df18f9af81d_key -iv $encrypted_3df18f9af81d_iv -in dist/gitcookie.sh.enc -out dist/gitcookie.sh -d
iv undefined
```

"iv undefined"?? It worked in https://travis-ci.org/mholt/caddy/builds/117517719. Whatever.

Thanks @tpng! I'll merge this in despite Travis having a hissy-fit. I'll also make you a collaborator so you can help with pull requests and bug fixes whenever you'd like. :smiley:

**Comment by vmattos** [comment]
:+1:

**Pull request merged**
