### PR TITLE
Add permission plugin directive

### PR DESCRIPTION
**Pull request by dhaavi**
I'm finally looking to make my plugin for caddy officially available.

The code currently lives at https://github.com/dhaavi/caddy-authplugger, but will be moved to https://github.com/dhaavi/caddy-permission within the next days.

Like a couple other plugins, this plugin is about authentication, but, additionally also about authorization:
Instead of just relaying authenticating users to another piece of software, it aims to bring fine-grained permission management to otherwise unsupported web applications.

For example, I've been using this code for over a year now to enforce fine-grained permissions on the filebrowser plugin. It plays fairly nice for the basic feature set, I must say. (I have not yet bothered to integrate all features with the permission model)

Technically speaking, it fetches and authenticates users via (1) the config file (HTTP Basic Auth), (2) an easy json-based api and/or (3) TLS client certificates. It then enforces a HTTP Method + Request Path permission model on the user. It also handles websockets.

I changed the name in order for users to better differentiate this plugin from other auth plugins.

EDITED TO ADD: There will be minor improvements and some maintenance within the next days (go modules!).

### CODE REVIEW

**Comment by dhaavi** [comment]
I done so far, just waiting for this to be merged in order to publish.
See https://github.com/dhaavi/caddy-permission.

**Comment by dhaavi** [comment]
If I understand correctly, I will have to wait for the next release of caddy to be able to use the new plugin with official images.

This is mildly confusing, as the plugin is already published on the docs page of caddy. Which means, that a download with plugin would succeed, but when trying to actually use the plugin it will complain: `Error during parsing: Unknown directive 'permission'`.

While technically not a bug, users will perceive this as a broken build and might even report it as such.

(I fixed the license)

**Comment by abiosoft** [comment]
@dhaavi you can temporarily disable your plugin in the developer portal

**Comment by dhaavi** [comment]
Thanks for the hint!

I didn't want to disable it, as users could be confused. I addad a note about compatibility, which I will remove as soon as caddy >=1.0.1 ships.

**Pull request merged**
